---
kind: kraken.component.api-target-mapper
apiVersion: v1
metadata:
  key: mef.sonata.api-target-mapper.inventory.common.read
  name: Inventory Connection API Common Mappers
  description: This operation retrieves a product entity
  version: 1
spec:
  endpoints:
    - id: retrieve product inventory detail by id
      mappers:
        request:
          - name: mapper.product.inventory.id
            title: Identifier of the Product
            description: ""
            source: "@{{id}}"
            sourceLocation: "PATH"
            target: ""
            targetLocation:
            requiredMapping: true
          - name: mapper.inventory.@{{productType}}.read.buyerId
            title: "The unique identifier of the organization that is acting as the a Buyer"
            source: "@{{buyerId}}"
            sourceLocation: "QUERY"
            target: ""
            targetType: string
            targetLocation: ""
            requiredMapping: false
        response:
          - name: mapper.product.inventory.read.status
            title:  the status of a MEF product
            description: ""
            target: "@{{status}}"
            targetType: enum
            targetLocation: BODY
            requiredMapping: true
            targetValues:
              - active
              - active.pendingChange
              - cancelled
              - pendingActive
              - pendingTerminate
              - suspended
              - suspendedPendingTerminate
              - terminated
            valueMapping: {}
            source: ""
            sourceLocation:
          - name: mapper.product.inventory.read.startDate
            title: The date from which the product starts
            description: ""
            target: "@{{startDate}}"
            targetLocation: BODY
            requiredMapping: true
            source: ""
            sourceLocation: ""
