---
kind: kraken.component.api-target-mapper
apiVersion: v1
metadata:
  key: mef.sonata.api-target-mapper.order.common.read.delete
  name: Order Delete Read API Common Mappers
  description: This operation retrieves a ProductOrder entity
  version: 2
spec:
  endpoints:
    - id: retrieve delete order by id
      mappers:
        request:
          - name: mapper.order.@{{productType}}.read.delete.buyerId
            title: "The unique identifier of the organization that is acting as a buyer"
            description: ""
            source: "@{{buyerId}}"
            sourceLocation: "QUERY"
            target: ""
            targetLocation: ""
            requiredMapping: false
          - name: mapper.order.@{{productType}}.read.delete.orderId
            title: "Order unique identifier"
            description: ""
            source: "@{{id}}"
            sourceLocation: "PATH"
            target: ""
            convertValue: "mef.sonata.api-target-mapper.order.@{{productType}}.add#mapper.order.@{{productType}}.add.orderId"
            targetLocation: ""
            requiredMapping: true
        response:
          - name: mapper.order.@{{productType}}.read.delete.completionDate
            title: "The order complete date"
            description: ""
            source: ""
            sourceLocation: "BODY"
            target: "@{{completionDate}}"
            checkPath: "$[?(@.state == 'completed'||@.state == 'failed'||@.state == 'partial'||@.state == 'rejected'||@.state == 'cancelled')]"
            deletePath: "$.completionDate"
            targetLocation: "BODY"
            requiredMapping: false
          - name: mapper.order.@{{productType}}.read.delete.instanceId
            title: "The instance id from the seller"
            description: ""
            source: ""
            sourceLocation: "BODY"
            target: "@{{productOrderItem[0].product.id}}"
            targetLocation: "BODY"
            requiredMapping: false
          - name: mapper.order.@{{productType}}.read.delete.productOrderItem.completionDate
            title: "Order item complete date"
            description: ""
            source: ""
            sourceLocation: "BODY"
            target: "@{{productOrderItem[0].completionDate}}"
            checkPath: "$.productOrderItem[?(@.state == 'completed')]"
            deletePath: "$.productOrderItem[?(@.state != 'completed')].completionDate"
            targetLocation: "BODY"
            requiredMapping: false
          - name: mapper.order.@{{productType}}.read.stateChange.state
            title: "State in state change history"
            description: ''
            source: ""
            target: '@{{productOrderItem[0].stateChange[*].state}}'
            targetType: enum
            targetValues:
              - acknowledged
              - assessingCancellation
              - held.assessingCharge
              - pending.assessingModification
              - cancelled
              - pendingCancellation
              - completed
              - failed
              - inProgress
              - partial
              - rejected
            valueMapping: {}
            replaceStar: true
            sourceLocation: BODY
            targetLocation: BODY
            customizedField: false
            requiredMapping: false
          - name: mapper.order.@{{productType}}.read.stateChange.changeDate
            title: "Date of state change"
            description: ''
            source: ''
            target: '@{{productOrderItem[0].stateChange[*].changeDate}}'
            replaceStar: true
            sourceLocation: BODY
            targetLocation: BODY
            customizedField: false
            requiredMapping: false