---
kind: kraken.component.api-target-mapper
apiVersion: v1
metadata:
  key: mef.sonata.api-target-mapper.order.common.delete
  name: Order Delete API Common Mappers
  description: This operation deletes a ProductOrder entity
  version: 2
spec:
  endpoints:
    - id: delete order
      mappers:
        request:
          - name: mapper.order.@{{productType}}.delete.buyerId
            title: "The unique identifier of the organization that is acting as a buyer"
            description: ""
            source: "@{{buyerId}}"
            sourceLocation: "QUERY"
            target: ""
            targetLocation: ""
            requiredMapping: false
          - name: mapper.order.@{{productType}}.delete.productId
            title: "The unique identifier of an in-service product that is the ordering subject"
            description: ""
            source: "@{{productOrderItem[*].product.id}}"
            sourceLocation: "BODY"
            sourceType: string
            target: ""
            targetLocation: ""
            requiredMapping: true
        response:
          - name: mapper.order.@{{productType}}.delete.state
            title: "The state of the product order"
            description: ""
            target: "@{{state}}"
            targetType: enum
            targetLocation: BODY
            requiredMapping: true
            targetValues:
              - acknowledged
              - assessingCancellation
              - held.assessingCharge
              - pending.assessingModification
              - cancelled
              - pendingCancellation
              - completed
              - failed
              - inProgress
              - partial
              - rejected
            valueMapping: {}
            source: ""
            sourceLocation: ""
          - name: mapper.order.@{{productType}}.delete.orderId
            title: "The order id from the seller"
            source: ""
            target: '@{{orderId}}'
            description: ""
            sourceLocation: BODY
            targetLocation: BODY
            requiredMapping: true