---
kind: kraken.component.api-target-mapper
apiVersion: v1
metadata:
  key: mef.sonata.api-target-mapper.order.common.modify
  name: Order Modify API Common Mappers
  description: This operation modifies a ProductOrder entity
  version: 1
spec:
  endpoints:
    - id: modify order
      mappers:
        request:
          - name: mapper.order.@{{productType}}.modify.buyerId
            title: The unique identifier of the organization that is acting as the a Buyer.
            description:
            target: ""
            source: "@{{buyerId}}"
            sourceLocation: QUERY
            targetLocation: ""
            customizedField: false
            requiredMapping: false
            replaceStar: true
          - name: mapper.order.@{{productType}}.modify.duration
            title: "order item Term duration"
            source: "@{{productOrderItem[0].requestedItemTerm.duration.amount}}"
            sourceLocation: BODY
            sourceType: integer
            discrete: true
            target: ""
            targetLocation: ""
            requiredMapping: false
          - name: mapper.order.@{{productType}}.modify.duration.unit
            title: "order item Term unit"
            source: "@{{productOrderItem[0].requestedItemTerm.duration.units}}"
            sourceType: enum
            sourceValues:
              - calendarYears
              - calendarMonths
              - calendarDays
              - calendarHours
              - calendarMinutes
              - businessDays
              - businessHours
              - businessMinutes
            sourceLocation: BODY
            target: ""
            targetLocation: ""
            valueMapping: { }
            requiredMapping: false
          - name: mapper.order.@{{productType}}.modify.endOfTermAction
            title: "MEFEndOfTermAction"
            source: "@{{productOrderItem[0].requestedItemTerm.endOfTermAction}}"
            sourceLocation: BODY
            sourceType: enum
            sourceValues:
              - roll
              - autoDisconnect
              - autoRenew
            target: ""
            targetLocation: BODY
            requiredMapping: false
          - name: mapper.order.@{{productType}}.modify.rollInterval.amount
            title: " quote item Term roll duration"
            source: "@{{productOrderItem[0].requestedItemTerm.rollInterval.amount}}"
            sourceLocation: BODY
            sourceType: integer
            discrete: true
            sourceConditionExpression:
            sourceConditions:
              - name: endOfTermAction
                key: "@{{productOrderItem[0].requestedItemTerm.endOfTermAction}}"
                val: roll
                operator: eq
            target: ""
            targetLocation: BODY
            requiredMapping: false
          - name: mapper.order.@{{productType}}.modify.rollInterval.units
            title: " quote item Term roll unit"
            source: "@{{productOrderItem[0].requestedItemTerm.rollInterval.units}}"
            sourceLocation: BODY
            sourceType: enum
            sourceValues:
              - calendarYears
              - calendarMonths
              - calendarDays
              - calendarHours
              - calendarMinutes
              - businessDays
              - businessHours
              - businessMinutes
            sourceConditionExpression:
            sourceConditions:
              - name: endOfTermAction
                key: "@{{productOrderItem[0].requestedItemTerm.endOfTermAction}}"
                val: roll
                operator: eq
            target: ""
            targetLocation: BODY
            requiredMapping: false
          - name: mapper.order.@{{productType}}.modify.bandwidthUnit
            title: "The unit of bandwidth"
            source: "@{{productOrderItem[0].product.productConfiguration.bandwidthUnit}}"
            sourceType: enum
            sourceValues:
              - MBPS
              - GBPS
            sourceLocation: BODY
            target: ""
            targetLocation: BODY
            valueMapping: { }
            requiredMapping: false
          - name: mapper.order.@{{productType}}.modify.bandwidth
            title: "Bandwidth of the ELINE"
            source: "@{{productOrderItem[0].product.productConfiguration.bandwidth}}"
            sourceLocation: BODY
            allowValueLimit: true
            sourceType: integer
            discrete: true
            sourceValues:
            target: ""
            targetLocation: BODY
            requiredMapping: false
          - name: mapper.order.@{{productType}}.modify.name
            title: "The name of the ELINE"
            source: "@{{productOrderItem[0].product.productConfiguration.name}}"
            sourceLocation: BODY
            sourceType: string
            target: ""
            targetLocation: BODY
            requiredMapping: false
          - name: mapper.order.@{{productType}}.modify.paymentType
            title: "The payment type of the ELINE"
            source: "@{{productOrderItem[0].product.productConfiguration.paymentType}}"
            sourceType: string
            sourceLocation: BODY
            target: ""
            targetLocation: BODY
            requiredMapping: false
          - name: mapper.order.@{{productType}}.modify.classOfService
            title: "The class of Service of the Eline"
            source: "@{{productOrderItem[0].product.productConfiguration.classOfService}}"
            sourceLocation: BODY
            sourceType: string
            target: ""
            targetLocation: BODY
            requiredMapping: false
          - name: mapper.order.@{{productType}}.modify.product.productConfiguration.buyerCompanyId
            title: "The Id of buyer Company"
            source: "@{{productOrderItem[0].product.productConfiguration.buyerCompanyId}}"
            sourceLocation: BODY
            sourceType: string
            target: ""
            targetLocation: BODY
            requiredMapping: false
          - name: mapper.order.@{{productType}}.modify.product.productConfiguration.destUNIMetroId
            title: "The metro id of the destination UNI"
            source: "@{{productOrderItem[0].product.productConfiguration.destUNIMetroId}}"
            sourceLocation: BODY
            sourceType: string
            target: ""
            targetLocation: BODY
            requiredMapping: false
          - name: mapper.order.@{{productType}}.modify.product.productConfiguration.type
            title: "customized product type"
            source: "@{{productOrderItem[0].product.productConfiguration.type}}"
            sourceLocation: BODY
            sourceType: string
            target: ""
            targetLocation: BODY
            requiredMapping: false
          - name: mapper.order.@{{productType}}.modify.srcUNI
            title: "source UNI or ENNI id"
            source: "@{{productOrderItem[0].product.productRelationship[0].id}}"
            sourceLocation: BODY
            sourceType: string
            target: ""
            targetLocation: BODY
            requiredMapping: false
          - name: mapper.order.@{{productType}}.modify.destUNI
            title: "destination UNI id"
            source: "@{{productOrderItem[0].product.productRelationship[1].id}}"
            sourceLocation: BODY
            sourceType: string
            target: ""
            targetLocation: BODY
            requiredMapping: false
          - name: mapper.order.@{{productType}}.modify.productOffering.id
            title: "id of a Product Offering"
            source: "@{{productOrderItem[0].product.productOffering.id}}"
            sourceLocation: BODY
            sourceType: string
            target: ""
            targetLocation: BODY
            requiredMapping: false
          - name: mapper.order.@{{productType}}.modify.product.id
            title: "The unique identifier of an in-service Product that is the ordering subject"
            source: "@{{productOrderItem[0].product.id}}"
            sourceLocation: BODY
            sourceType: string
            target: ""
            targetLocation: BODY
            requiredMapping: true
        response:
          - name: mapper.order.@{{productType}}.modify.state
            title: Order State
            source: ""
            target: "@{{state}}"
            targetType: enum
            description:
            replaceStar: true
            targetValues:
              - acknowledged
              - assessingCancellationacknowledged
              - held.assessingCharge
              - pending.assessingModification
              - cancelled
              - pendingCancellation
              - completed
              - failed
              - inProgress
              - partial
              - rejected
            valueMapping: { }
            sourceLocation: BODY
            targetLocation: BODY
            customizedField: false
            requiredMapping: true
          - name: mapper.order.@{{productType}}.modify.orderId
            title: order Id from seller
            source: ""
            target: "@{{orderId}}"
            description: orderId mapping
            sourceLocation: BODY
            targetLocation: BODY
            customizedField: false
            requiredMapping: true