---
kind: kraken.component.api-target-mapper
apiVersion: v1
metadata:
  key: mef.sonata.api-target-mapper.inventory.uni.read
  name: Inventory Port API Detail
  description: This operation retrieves a product entity
  version: 13
spec:
  trigger:
    path: /mefApi/sonata/productInventory/v7/product/{id}
    method: get
    productType: uni
  endpoints:
    - id: retrieve uni product inventory detail by id
      path: ""
      method: ""
      serverKey: ""
      mappers:
        schemaRef:
          ref: "classpath:/mef-sonata/api-common-mappers/api-target-mapper.inventory.common.read.yaml"
          params:
            - key: productType
              val: uni
        request:
        response: