---
kind: kraken.component.api-target-mapper
apiVersion: v1
metadata:
  key: mef.sonata.api-target-mapper.order.eline.read
  name:  Mapper Of Reading Order Connection
  description: This operation retrieves a ProductOrder entity
  version: 3
spec:
  trigger:
    path: /mefApi/sonata/productOrderingManagement/v10/productOrder/{id}
    method: get
    productType: access_e_line
    actionType: add
  endpoints:
    - path: ""
      method: ""
      serverKey: ""
      mappers:
        schemaRef:
          ref: "classpath:/mef-sonata/api-common-mappers/api-target-mapper.order.common.read.add.yaml"
          params:
            - key: productType
              val: eline
        request:
        response:
