---
kind: kraken.component.api-target-mapper
apiVersion: v1
metadata:
  key: mef.sonata.api-target-mapper.order.eline.read.delete
  name:  Mapper Of Reading Order Connection with Delete Action
  description: This operation retrieves a ProductOrder entity
spec:
  trigger:
    path: /mefApi/sonata/productOrderingManagement/v10/productOrder/{id}
    method: get
    productType: access_e_line
    actionType: delete
  endpoints:
    - path: ""
      method: ""
      serverKey: ""
      mappers:
        request:
          - name: mapper.order.eline.read.delete.buyerId
            title: "The unique identifier of the organization that is acting as the a Buyer."
            description: ""
            source: "@{{buyerId}}"
            sourceLocation: "QUERY"
            target: ""
            targetLocation: "PATH"
            requiredMapping: false
          - name: mapper.order.eline.read.delete.orderId
            title: "Order Unique Identifier."
            description: ""
            source: "@{{id}}"
            sourceLocation: "PATH"
            target: ""
            convertValue: "mef.sonata.api-target-mapper.order.eline.add#mapper.order.eline.add.orderId"
            targetLocation: ""
            requiredMapping: true
        response:
          - name: mapper.order.eline.read.delete.state
            title: "ProductOrderState"
            description: ""
            target: "@{{state}}"
            targetType: enum
            targetLocation: BODY
            requiredMapping: true
            targetValues:
              - acknowledged
              - assessingCancellation
              - held.assessingCharge
              - pending.assessingModification
              - cancelled
              - pendingCancellation
              - completed
              - failed
              - inProgress
              - partial
              - rejected
            valueMapping: {}
            source: ""
            sourceLocation: "BODY"
          - name: mapper.order.eline.read.delete.completionDate
            title: "order complete date"
            description: ""
            source: ""
            sourceLocation: "BODY"
            target: "@{{completionDate}}"
            targetLocation: "BODY"
            requiredMapping: false
          - name: mapper.order.eline.read.delete.instanceId
            title: "instance id from seller"
            description: ""
            source: ""
            sourceLocation: "BODY"
            target: "@{{productOrderItem[0].product.id}}"
            targetLocation: "BODY"
            requiredMapping: false
          - name: mapper.order.eline.read.delete.productOrderItem.completionDate
            title: "order item complete date"
            description: ""
            source: ""
            sourceLocation: "BODY"
            target: "@{{productOrderItem[0].completeDate}}"
            targetLocation: "BODY"
            requiredMapping: false
          - name: mapper.order.eline.read.delete.productOrderItem.expectedCompleteDate
            title: "order item expected complete date"
            description: ""
            source: ""
            sourceLocation: "BODY"
            target: "@{{productOrderItem[0].expectedCompleteDate}}"
            targetLocation: "BODY"
            requiredMapping: false