---
kind: kraken.component.api-target-mapper
apiVersion: v1
metadata:
  key: mef.sonata.api-target-mapper.quote.eline.add.sync
  name: Mapper Of Creating Quote Eline
  description: This operation creates a Quote entity
  version: 4
spec:
  trigger:
    path: /mefApi/sonata/quoteManagement/v8/quote
    method: post
    productType: access_e_line
    actionType: add
    quoteLevel: firm
    syncMode: true
  endpoints:
    - id: create quote for connection
      path: /api/pricing/calculate
      method: post
      serverKey: mef.sonata.api-target-spec.con1718940696857
      mappers:
        request:
          - name: mapper.quote.eline.add.sync.duration.amount
            title: "quote item Term duration"
            source: "@{{quoteItem[0].requestedQuoteItemTerm.duration.amount}}"
            sourceLocation: BODY
            sourceType: integer
            discrete: true
            target: ""
            targetLocation: BODY
            requiredMapping: true
          - name: mapper.quote.eline.add.sync.duration.units
            title: "quote item Term unit"
            source: "@{{quoteItem[0].requestedQuoteItemTerm.duration.units}}"
            sourceLocation: BODY
            sourceType: enum
            sourceValues:
              - calendarYears
              - calendarMonths
              - calendarDays
              - calendarHours
              - calendarMinutes
              - businessDays
              - businessHours
              - businessMinutes
            valueMapping: {}
            target: ""
            targetLocation: BODY
            requiredMapping: true
          - name: mapper.quote.eline.add.sync.endOfTermAction
            title: "MEFEndOfTermAction"
            source: "@{{quoteItem[0].requestedQuoteItemTerm.endOfTermAction}}"
            sourceLocation: BODY
            sourceType: enum
            sourceValues:
              - roll
              - autoDisconnect
              - autoRenew
            valueMapping: {}
            target: ""
            targetLocation: BODY
            requiredMapping: true
          - name: mapper.quote.eline.add.sync.rollInterval.amount
            title: "quote item Term roll duration"
            source: "@{{quoteItem[0].requestedQuoteItemTerm.rollInterval.amount}}"
            sourceLocation: BODY
            sourceType: integer
            discrete: true
            sourceConditionExpression:
            sourceConditions:
              - name: endOfTermAction
                key: "@{{quoteItem[0].requestedQuoteItemTerm.endOfTermAction}}"
                val: roll
                operator: eq
            target: ""
            targetLocation: BODY
            requiredMapping: false
          - name: mapper.quote.eline.add.sync.rollInterval.units
            title: "quote item Term roll unit"
            source: "@{{quoteItem[0].requestedQuoteItemTerm.rollInterval.units}}"
            sourceLocation: BODY
            sourceType: enum
            sourceValues:
              - calendarYears
              - calendarMonths
              - calendarDays
              - calendarHours
              - calendarMinutes
              - businessDays
              - businessHours
              - businessMinutes
            valueMapping: {}
            sourceConditionExpression:
            sourceConditions:
              - name: endOfTermAction
                key: "@{{quoteItem[0].requestedQuoteItemTerm.endOfTermAction}}"
                val: roll
                operator: eq
            target: ""
            targetLocation: BODY
            requiredMapping: false
          - name: mapper.quote.eline.add.sync.place0.id
            title: "The id of the place where source location of the quoted product"
            source: "@{{quoteItem[0].product.place[0].id}}"
            sourceLocation: BODY
            sourceType: string
            target: ""
            targetLocation: BODY
            requiredMapping: true
          - name: mapper.quote.eline.add.sync.place1.id
            title: "The id of the place where destination location of the quoted product"
            source: "@{{quoteItem[0].product.place[1].id}}"
            sourceLocation: BODY
            sourceType: string
            target: ""
            targetLocation: BODY
            requiredMapping: true
          - name: mapper.quote.eline.add.sync.productConfiguration.bandwidth
            title: "Bandwidth of the Eline"
            source: "@{{quoteItem[0].product.productConfiguration.bandwidth}}"
            sourceLocation: BODY
            allowValueLimit: true
            sourceType: integer
            discrete: true
            sourceValues:
            target: ""
            targetLocation: BODY
            requiredMapping: true
          - name: mapper.quote.eline.add.sync.productConfiguration.bandwidthUnit
            title: "The unit of bandwidth"
            source: "@{{quoteItem[0].product.productConfiguration.bandwidthUnit}}"
            sourceLocation: BODY
            sourceType: enum
            sourceValues:
              - GBPS
              - MBPS
            valueMapping: {}
            target: ""
            targetLocation: BODY
            requiredMapping: true
          - name: mapper.quote.eline.add.sync.productConfiguration.classOfService
            title: "The class of Service of the Eline"
            source: "@{{quoteItem[0].product.productConfiguration.classOfService}}"
            sourceLocation: BODY
            sourceType: string
            target: ""
            targetLocation: BODY
            requiredMapping: false
          - name: mapper.quote.eline.add.sync.productConfiguration.paymentType
            title: "The payment type of the Eline"
            source: "@{{quoteItem[0].product.productConfiguration.paymentType}}"
            sourceLocation: BODY
            sourceType: string
            target: ""
            targetLocation: BODY
            requiredMapping: false
          - name: mapper.quote.eline.add.sync.productOffering.id
            title: "The id of the quoted product offering"
            source: "@{{quoteItem[0].product.productOffering.id}}"
            sourceLocation: BODY
            sourceType: string
            target: ""
            targetLocation: BODY
            requiredMapping: false
        response:
          - name: mapper.quote.eline.add.sync.unitOfMeasure
            title: "Unit of Measure if price depending on it"
            description: ""
            source: ""
            sourceLocation: BODY
            target: "@{{quoteItem[0].quoteItemPrice[*].unitOfMeasure}}"
            targetLocation: BODY
            requiredMapping: false
          - name: mapper.quote.eline.add.sync.price.unit
            title: "Currency (ISO4217 norm uses 3 letters to define the currency)"
            description: ""
            source: ""
            sourceLocation: BODY
            target: "@{{quoteItem[0].quoteItemPrice[*].price.dutyFreeAmount.unit}}"
            targetLocation: BODY
            requiredMapping: true
          - name: mapper.quote.eline.add.sync.price.value
            title: "Duty free price value"
            description: ""
            source: ""
            sourceLocation: ""
            target: "@{{quoteItem[0].quoteItemPrice[*].price.dutyFreeAmount.value}}"
            targetLocation: BODY
            requiredMapping: true
            replaceStar: true
            checkPath: "$['quoteItem'][0]['quoteItemPrice'][0]['price']['dutyFreeAmount']['value']"
            deletePath: "$.quoteItem[0].quoteItemPrice"
          - name: mapper.quote.eline.add.sync.taxRate
            title: "Price Tax Rate. Unit: [%]. E.g. value 16 stand for 16% tax"
            description: ""
            source: ""
            sourceLocation: BODY
            target: "@{{quoteItem[0].quoteItemPrice[*].price.taxRate}}"
            targetLocation: BODY
            requiredMapping: false
          - name: mapper.quote.eline.add.sync.taxIncludedAmount.unit
            title: "Currency (ISO4217 norm uses 3 letters to define the currency)"
            description: ""
            source: ""
            sourceLocation: BODY
            target: "@{{quoteItem[0].quoteItemPrice[*].price.taxIncludedAmount.unit}}"
            targetLocation: BODY
            requiredMapping: false
          - name: mapper.quote.eline.add.sync.taxIncludedAmount.value
            title: "Tax included price value"
            description: ""
            source: ""
            sourceLocation: BODY
            target: "@{{quoteItem[0].quoteItemPrice[*].price.taxIncludedAmount.value}}"
            targetLocation: BODY
            requiredMapping: false
          - name: mapper.quote.eline.add.sync.quoteItemPrice.name
            title: "Name of the quote item price"
            description: ""
            source: ""
            sourceLocation: BODY
            target: "@{{quoteItem[0].quoteItemPrice[*].name}}"
            targetLocation: BODY
            requiredMapping: false
          - name: mapper.quote.eline.add.sync.quoteItemPrice.priceType
            title: "Indicates if the price is for recurring or non-recurring charges"
            description: ""
            source: ""
            sourceLocation: BODY
            target: "@{{quoteItem[0].quoteItemPrice[*].priceType}}"
            targetType: enum
            targetLocation: BODY
            requiredMapping: false
            targetValues:
              - recurring
              - nonRecurring
              - usageBased
            valueMapping: {}
          - name: mapper.quote.eline.add.sync.quoteItemPrice.description
            title: "Description of the quote item price"
            description: ""
            source: ""
            sourceLocation: BODY
            target: "@{{quoteItem[0].quoteItemPrice[*].description}}"
            targetLocation: BODY
            requiredMapping: false
          - name: mapper.quote.eline.add.sync.quoteItemPrice.recurringChargePeriod
            title: "Used for a recurring charge to indicate period"
            description: ""
            source: ""
            sourceLocation: BODY
            target: "@{{quoteItem[0].quoteItemPrice[*].recurringChargePeriod}}"
            targetType: enum
            targetLocation: BODY
            requiredMapping: false
            replaceStar: true
            targetValues:
              - hour
              - day
              - week
              - month
              - year
            valueMapping: {}