---
kind: kraken.component.api-target-mapper
apiVersion: v1
metadata:
  key: mef.sonata.api-target-mapper.quote.eline.read.sync
  name: Mapper Of Reading Quote Eline
  description: This operation retrieves a Quote entity. Attribute selection is enabled for all first level attributes.
  version: 1
spec:
  trigger:
    path: /mefApi/sonata/quoteManagement/v8/quote/{id}
    method: get
    productType: access_e_line
    quoteLevel: firm
    syncMode: true
  endpoints:
    - id: retrieve quote for connection
      path: ""
      method: ""
      serverKey: ""
      mappers:
        pathRules:
          - name: mapper.quite.eline.read.sync.pathRule.state
            checkPath: "$[?(@.state != 'unableToProvide')]"
            deletePath: "$.validFor,  $.quoteLevel"
            insertPath:
              - key: "$.quoteItem[0].terminationError.code"
                val: "otherIssue"
              - key: "$.quoteItem[0].terminationError.value"
                val: "the quoted item is not available"
        request:
        response: