---
kind: kraken.component.api-target-mapper
apiVersion: v1
metadata:
  key: mef.sonata.api-target-mapper.order.eline.read.modify
  name:  Mapper Of Reading Order Connection with Modify Action
  description: This operation retrieves a ProductOrder entity
spec:
  trigger:
    path: /mefApi/sonata/productOrderingManagement/v10/productOrder/{id}
    method: get
    productType: access_e_line
    actionType: modify
  endpoints:
    - path: ""
      method: ""
      serverKey: ""
      mappers:
        schemaRef:
          ref: "classpath:/mef-sonata/api-common-mappers/api-target-mapper.order.common.read.delete.yaml"
          params:
            - key: productType
              val: eline