---
kind: kraken.component.api-target-mapper
apiVersion: v1
metadata:
  key: mef.sonata.api-target-mapper.address.retrieve
  name: Mapper Of Retrieving Geographic Address
  description: This operation retrieves a GeographicAddress entity
  version: 3
spec:
  trigger:
    path: /mefApi/sonata/geographicAddressManagement/v7/geographicAddress/{id}
    method: get
    addressType: FieldedAddress
  endpoints:
    - id: retrieve address
      path: ""
      method: ""
      serverKey: ""
      mappers:
        request:
          - name: mapper.address.retrieve.id
            title: "Identifier of the GeographicAddress"
            description: ""
            source: "@{{id}}"
            sourceLocation: "PATH"
            target: ""
            targetLocation: ""
            requiredMapping: true
        response:
          - name: mapper.address.validation.id
            title: "Identifier of the GeographicAddress"
            description: ""
            source: ""
            sourceLocation: ""
            target: "@{{id}}"
            targetType: string
            targetLocation: BODY
            requiredMapping: true
          - name: mapper.address.validation.country
            title: "The country of the Geographic Address"
            description: ""
            source: ""
            sourceLocation: ""
            target: "@{{associatedGeographicAddress.country}}"
            targetType: string
            targetLocation: BODY
            requiredMapping: false
          - name: mapper.address.validation.city
            title: "The city of the Geographic Address"
            description: ""
            source: ""
            sourceLocation: ""
            target: "@{{associatedGeographicAddress.city}}"
            targetType: string
            targetLocation: BODY
            requiredMapping: false
          - name: mapper.address.validation.streetName
            title: "The street of the Geographic Address"
            description: ""
            source: ""
            sourceLocation: ""
            target: "@{{associatedGeographicAddress.streetName}}"
            targetType: string
            targetLocation: BODY
            requiredMapping: false
          - name: address.validation.locality.mapper
            title: "The metroId of the identified alternate Geographic Address"
            description: ""
            source: ""
            sourceLocation: ""
            target: "@{{associatedGeographicAddress.locality}}"
            targetType: string
            targetLocation: BODY
            requiredMapping: false
            replaceStar: false