---
kind: kraken.component.api-target-mapper
apiVersion: v1
metadata:
  key: mef.sonata.api-target-mapper.order.uni.read
  name: Mapper Of Reading Order Port
  description: This operation retrieves a ProductOrder entity
  version: 3
spec:
  trigger:
    path: /mefApi/sonata/productOrderingManagement/v10/productOrder/{id}
    method: get
    productType: uni
    actionType: add
  endpoints:
    - id: retrieve connection detail by id
      path: ""
      method: ""
      serverKey: ""
      mappers:
        request:
          - name: mapper.order.uni.read.buyerId
            title: "The unique identifier of the organization that is acting as the a Buyer."
            description: ""
            source: "@{{buyerId}}"
            sourceLocation: "QUERY"
            target: ""
            targetLocation: ""
            requiredMapping: false
          - name: mapper.order.uni.read.orderId
            title: "Order Unique Identifier."
            description: ""
            source: "@{{id}}"
            sourceLocation: "PATH"
            target: ""
            convertValue: "mef.sonata.api-target-mapper.order.uni.add#mapper.order.uni.add.orderId"
            targetLocation: ""
            requiredMapping: true
        response:
          - name: mapper.order.uni.read.state
            title: "ProductOrderState"
            description: ""
            target: "@{{state}}"
            targetType: enum
            targetLocation: BODY
            requiredMapping: true
            targetValues:
              - acknowledged
              - assessingCancellation
              - held.assessingCharge
              - pending.assessingModification
              - cancelled
              - pendingCancellation
              - completed
              - failed
              - inProgress
              - partial
              - rejected
            valueMapping: {}
            source: ""
            sourceLocation: "BODY"
          - name: mapper.order.uni.read.completionDate
            title: "order complete date"
            description: ""
            source: ""
            sourceLocation: "BODY"
            target: "@{{completionDate}}"
            checkPath: "$[?(@.state == 'completed'||@.state == 'failed'||@.state == 'partial'||@.state == 'rejected'||@.state == 'cancelled')]"
            deletePath: "$.completionDate"
            targetLocation: "BODY"
            requiredMapping: false
          - name: mapper.order.uni.read.instanceId
            title: "instance id from seller"
            description: ""
            source: ""
            sourceLocation: "BODY"
            target: "@{{productOrderItem[0].product.id}}"
            targetLocation: "BODY"
            requiredMapping: false
          - name: mapper.order.uni.read.productOrderItem.completionDate
            title: "order item complete date"
            description: ""
            source: ""
            sourceLocation: "BODY"
            target: "@{{productOrderItem[0].completionDate}}"
            targetLocation: "BODY"
            checkPath: "$.productOrderItem[?(@.state == 'completed')]"
            deletePath: "$.productOrderItem[?(@.state != 'completed')].completionDate"
            requiredMapping: false
          - name: mapper.order.uni.read.productOrderItem.expectedCompleteDate
            title: "order item expected complete date"
            description: ""
            source: ""
            sourceLocation: "BODY"
            target: "@{{productOrderItem[0].expectedCompletionDate}}"
            targetLocation: "BODY"
            requiredMapping: false
          - name: mapper.order.uni.read.stateChange.state
            title: state in state change history
            description: ''
            source: ""
            target: '@{{productOrderItem[0].stateChange[*].state}}'
            targetType: enum
            targetValues:
              - acknowledged
              - assessingCancellation
              - held.assessingCharge
              - pending.assessingModification
              - cancelled
              - pendingCancellation
              - completed
              - failed
              - inProgress
              - partial
              - rejected
            valueMapping: {}
            replaceStar: true
            sourceLocation: BODY
            targetLocation: BODY
            customizedField: false
            requiredMapping: false
          - name: mapper.order.uni.read.stateChange.changeDate
            title: change date in state change history
            description: ''
            source: ''
            target: '@{{productOrderItem[0].stateChange[*].changeDate}}'
            replaceStar: true
            sourceLocation: BODY
            targetLocation: BODY
            customizedField: false
            requiredMapping: false