---
kind: kraken.component.api-target-mapper
apiVersion: v1
metadata:
  key: mef.sonata.api-target-mapper.quote.uni.read
  name: Mapper Of Reading Quote UNI
  description: This operation retrieves a Quote entity. Attribute selection is enabled for all first level attributes.
  version: 4
spec:
  trigger:
    path: /mefApi/sonata/quoteManagement/v8/quote/{id}
    method: get
    productType: uni
    quoteLevel: firm
    syncMode: false
  endpoints:
    - id: retrieve quote for port
      path: ""
      method: ""
      serverKey: ""
      mappers:
        request:
        response:
          - name: mapper.quote.uni.read.state
            title: "The quote state"
            description: ""
            source: ""
            sourceLocation: ""
            target: "@{{quoteItem[*].state}}"
            targetType: enum
            targetLocation: BODY
            requiredMapping: true
            targetValues:
              - accepted
              - acknowledged
              - answered
              - approved.orderable
              - approved.orderableAlternate
              - cancelled
              - unableToProvide
              - declined
              - expired
              - inProgress
              - inProgress.draft
              - rejected
            valueMapping: {}
          - name: mapper.quote.uni.read.price.value
            title: "The quote price value"
            description: ""
            source: ""
            sourceLocation:
            target: "@{{quoteItem[0].quoteItemPrice[*].price.dutyFreeAmount.value}}"
            targetLocation: BODY
            requiredMapping: true
          - name: mapper.quote.uni.read.price.unit
            title: "The quote price unit"
            description: ""
            source: ""
            sourceLocation: ""
            target: "@{{quoteItem[0].quoteItemPrice[*].price.dutyFreeAmount.unit}}"
            targetLocation: BODY
            requiredMapping: true