---
kind: kraken.component.api-target-mapper
apiVersion: v1
metadata:
  key: mef.sonata.api-target-mapper.inventory.eline.read
  name: Inventory Connection API
  description: This operation retrieves a product entity
  version: 11
spec:
  trigger:
    path: /mefApi/sonata/productInventory/v7/product/{id}
    method: get
    productType: access_e_line
  endpoints:
    - id: retrieve eline product inventory detail by id
      path: ""
      method: ""
      serverKey: ""
      mappers:
        schemaRef:
          ref: "classpath:/mef-sonata/api-common-mappers/api-target-mapper.inventory.common.read.yaml"
          params:
            - key: productType
              val: eline
        request:
        response: