---
kind: kraken.component.api-target-mapper
apiVersion: v1
metadata:
  key: mef.sonata.api-target-mapper.poq.eline.add
  name: Product Offering Qualification (POQ) API
  description: | 
    A request initiated by the Buyer to determine whether the Seller is
    able to deliver a product or set of products from among their product
    offerings, at the Buyer's location(s); or modify a previously purchased
    product. The Seller also provides estimated time intervals to complete
    these deliveries. Reference: MEF 79 (Sn 8.4).
spec:
  trigger:
    path: /mefApi/sonata/productOfferingQualification/v7/productOfferingQualification
    method: post
    productType: access_e_line
    actionType: add
    provideAlternative: false
    syncMode: true
  endpoints:
    - id: create a product offering qualification for connection
      path: ""
      method: ""
      mappers:
        schemaRef:
          ref: "classpath:/mef-sonata/api-common-mappers/api-target-mapper.poq.common.add.yaml"
          params:
            - key: productType
              val: eline
        request:
          - name: mapper.poq.eline.add.place1.id
            source: "@{{productOfferingQualificationItem[0].product.place[1].id}}"
            sourceLocation: BODY
            sourceType: string
            target: ""
            targetLocation: ""
            requiredMapping: true
        response: