---
kind: kraken.component.api-target-mapper
apiVersion: v1
metadata:
  key: mef.sonata.api-target-mapper.order.uni.read.delete
  name: Mapper Of Reading Order Port with Delete Action
  description: This operation retrieves a ProductOrder entity
spec:
  trigger:
    path: /mefApi/sonata/productOrderingManagement/v10/productOrder/{id}
    method: get
    productType: uni
    actionType: delete
  endpoints:
    - id: retrieve connection detail by id
      path: ""
      method: ""
      serverKey: ""
      mappers:
        schemaRef:
          ref: "classpath:/mef-sonata/api-common-mappers/api-target-mapper.order.common.read.delete.yaml"
          params:
            - key: productType
              val: uni
        request:
        response:
          - name: mapper.order.uni.read.delete.state
            title: "ProductOrderState"
            description: ""
            target: "@{{state}}"
            targetType: enum
            targetLocation: BODY
            requiredMapping: true
            targetValues:
              - acknowledged
              - assessingCancellation
              - held.assessingCharge
              - pending.assessingModification
              - cancelled
              - pendingCancellation
              - completed
              - failed
              - inProgress
              - partial
              - rejected
            valueMapping: { }
            source: ""
            sourceLocation: "BODY"
            renderCheck: false