---
kind: kraken.component.api-target-mapper
apiVersion: v1
metadata:
  name: Mapper Of Creating Order Connection
  version: 29
  key: mef.sonata.api-target-mapper.order.eline.add
  description: This operation creates a ProductOrder entity
spec:
  trigger:
    path: "/mefApi/sonata/productOrderingManagement/v10/productOrder"
    method: post
    actionType: add
    productType: access_e_line
  endpoints:
    - id: create connection order
      path: ""
      method: ""
      serverKey: ""
      mappers:
        request:
          - name: mapper.order.eline.add.buyerId
            title: The unique identifier of the organization that is acting as the a Buyer.
            source: "@{{buyerId}}"
            target: ""
            description:
            replaceStar: true
            sourceLocation: QUERY
            targetLocation: ""
            customizedField: false
            requiredMapping: false
          - name: mapper.order.eline.add.duration
            title: "order item Term duration"
            source: "@{{productOrderItem[0].requestedItemTerm.duration.amount}}"
            target: ""
            sourceLocation: BODY
            targetLocation: ""
            requiredMapping: true
          - name: mapper.order.eline.add.duration.unit
            title: "order item Term unit"
            source: "@{{productOrderItem[0].requestedItemTerm.duration.units}}"
            target: ""
            sourceType: enum
            sourceValues:
              - calendarYears
              - calendarMonths
              - calendarDays
              - calendarHours
              - calendarMinutes
              - businessDays
              - businessHours
              - businessMinutes
            sourceLocation: BODY
            targetLocation: ""
            valueMapping: {}
            requiredMapping: true
          - name: mapper.order.eline.add.endOfTermAction
            title: "MEFEndOfTermAction"
            source: "@{{productOrderItem[0].requestedItemTerm.endOfTermAction}}"
            target: ""
            sourceLocation: BODY
            targetLocation: BODY
            requiredMapping: true
          - name: mapper.order.eline.add.rollInterval.amount
            title: " quote item Term roll duration"
            source: "@{{productOrderItem[0].requestedItemTerm.rollInterval.amount}}"
            target: ""
            sourceLocation: BODY
            targetLocation: BODY
            requiredMapping: false
          - name: mapper.order.eline.add.rollInterval.units
            title: " quote item Term roll unit"
            source: "@{{productOrderItem[0].requestedItemTerm.rollInterval.units}}"
            target: ""
            sourceLocation: BODY
            targetLocation: BODY
            requiredMapping: false
          - name: mapper.order.eline.add.bandwidthUnit
            title: "The unit of bandwidth"
            source: "@{{productOrderItem[0].product.productConfiguration.bandwidthUnit}}"
            sourceType: enum
            sourceValues:
              - MBPS
              - GBPS
            target: ""
            sourceLocation: BODY
            targetLocation: BODY
            valueMapping: {}
            requiredMapping: true
          - name: mapper.order.eline.add.bandwidth
            title: "Bandwidth of the ELINE"
            source: "@{{productOrderItem[0].product.productConfiguration.bandwidth}}"
            target: ""
            sourceLocation: BODY
            sourceType: discreteInt
            sourceValues:
              - 1000
              - 10000
            targetLocation: BODY
            requiredMapping: true
          - name: mapper.order.eline.add.name
            title: "The name of the ELINE"
            source: "@{{productOrderItem[0].product.productConfiguration.name}}"
            target: ""
            sourceLocation: BODY
            targetLocation: BODY
            requiredMapping: false
          - name: mapper.order.eline.add.paymentType
            title: "The payment type of the ELINE"
            source: "@{{productOrderItem[0].product.productConfiguration.paymentType}}"
            target: ""
            sourceLocation: BODY
            targetLocation: BODY
            requiredMapping: false
          - name: mapper.order.eline.add.classOfService
            title: "The class of Service of the Eline"
            source: "@{{productOrderItem[0].product.productConfiguration.classOfService}}"
            target: ""
            sourceLocation: BODY
            targetLocation: BODY
            requiredMapping: false
          - name: mapper.order.eline.add.srcUNI
            title: "source UNI or ENNI id"
            source: "@{{productOrderItem[0].product.productRelationship[0].id}}"
            target: ""
            sourceLocation: BODY
            targetLocation: BODY
            requiredMapping: true
          - name: mapper.order.eline.add.destUNI
            title: "destination UNI id"
            source: "@{{productOrderItem[0].product.productRelationship[1].id}}"
            target: ""
            sourceLocation: BODY
            targetLocation: BODY
            requiredMapping: true
          - name: mapper.order.eline.add.productOffering.id
            title: "id of a Product Offering"
            source: "@{{productOrderItem[0].product.productOffering.id}}"
            target: ""
            sourceLocation: BODY
            targetLocation: BODY
            requiredMapping: true
        response:
          - name: mapper.order.eline.add.state
            title: Order State
            source: ""
            target: "@{{state}}"
            targetType: enum
            description:
            replaceStar: true
            targetValues:
              - acknowledged
              - assessingCancellationacknowledged
              - held.assessingCharge
              - pending.assessingModification
              - cancelled
              - pendingCancellation
              - completed
              - failed
              - inProgress
              - partial
              - rejected
            valueMapping: {}
            sourceLocation: BODY
            targetLocation: BODY
            customizedField: false
            requiredMapping: true
          - name: mapper.order.eline.add.orderId
            title: order Id from seller
            source: ""
            target: "@{{orderId}}"
            description: orderId mapping
            sourceLocation: BODY
            targetLocation: BODY
            customizedField: false
            requiredMapping: true
          - name: mapper.order.eline.add.instanceId
            title: instance id from seller
            source: ""
            target: "@{{instanceId}}"
            description: ''
            sourceLocation: BODY
            targetLocation: BODY
            customizedField: false
            requiredMapping: false
          - name: mapper.order.eline.add.product.id
            title: product instance id
            description: ""
            source: ""
            sourceLocation: BODY
            target: "@{{productOrderItem[0].product.id}}"
            targetLocation: BODY
            customizedField: false
            requiredMapping: false
          - name: mapper.order.eline.add.term.duration
            title: order item Term duration
            description: ""
            source: ""
            sourceLocation: ""
            target: "@{{productOrderItem[0].itemTerm.duration.amount}}"
            targetLocation: BODY
            customizedField: false
            requiredMapping: true
          - name: mapper.order.eline.add.term.units
            title: order item Term unit
            description: ""
            source: ""
            sourceLocation: ""
            target: "@{{productOrderItem[0].itemTerm.duration.units}}"
            targetType: enum
            targetLocation: BODY
            customizedField: false
            requiredMapping: true
            targetValues:
              - calendarYears
              - calendarMonths
              - calendarDays
              - calendarHours
              - calendarMinutes
              - businessDays
              - businessHours
              - businessMinutes
            valueMapping: {}
          - name: mapper.order.eline.add.term.endOfTermAction
            title: MEFEndOfTermAction
            description: ""
            source: ""
            sourceLocation: ""
            target: "@{{productOrderItem[0].itemTerm.endOfTermAction}}"
            targetLocation: BODY
            customizedField: false
            requiredMapping: true
          - name: mapper.order.eline.add.term.rollInterval.amount
            title: order item Term roll duration
            description: ""
            source: ""
            sourceLocation: ""
            target: "@{{productOrderItem[0].itemTerm.rollInterval.amount}}"
            targetLocation: BODY
            customizedField: false
            requiredMapping: false
          - name: mapper.order.eline.add.term.rollInterval.unit
            title: order item Term roll unit
            description: ""
            source: ""
            sourceLocation: ""
            target: "@{{productOrderItem[0].itemTerm.rollInterval.units}}"
            targetLocation: BODY
            customizedField: false
            requiredMapping: false
          - name: mapper.order.eline.add.term.name
            title: order item Term name
            description: ""
            source: ""
            sourceLocation: ""
            target: "@{{productOrderItem[0].itemTerm.name}}"
            targetLocation: BODY
            customizedField: false
            requiredMapping: true

