---
kind: kraken.component.api-target-mapper
apiVersion: v1
metadata:
  key: mef.sonata.api-target-mapper.quote.uni.add.sync
  name: Mapper Of Creating Quote UNI
  description: This operation creates a Quote entity
  version: 3
spec:
  trigger:
    path: /mefApi/sonata/quoteManagement/v8/quote
    method: post
    productType: uni
    actionType: add
    quoteLevel: firm
    syncMode: true
  endpoints:
    - id: create quote for port
      path: ""
      method: ""
      serverKey: ""
      mappers:
        pathRules:
          - name: mapper.quite.uni.add.sync.pathRule.state
            checkPath: "$[?(@.state != 'unableToProvide')]"
            deletePath: "$.validFor"
            insertPath:
              - key: "$.quoteItem[0].terminationError.code"
                val: "otherIssue"
              - key: "$.quoteItem[0].terminationError.value"
                val: "the quoted item is not available"
        schemaRef:
          ref: "classpath:/mef-sonata/api-common-mappers/api-target-mapper.quote.common.add.sync.yaml"
          params:
            - key: productType
              val: uni
        request:
        response: