
---
kind: kraken.component.api-target-mapper
apiVersion: v1
metadata:
  key: mef.sonata.api-target-mapper.order.eline.delete
  name:  Mapper Of Deleting Order Connection
  description: This operation deletes a ProductOrder entity
  version: 3
spec:
  trigger:
    path: /mefApi/sonata/productOrderingManagement/v10/productOrder
    method: post
    productType: access_e_line
    actionType: delete
  supportedCase:
    type: ONE_TO_ONE_AND_ONE_TO_MANY
  workflow:
    enabled: false
    synchronous: false
    key: mef.sonata.api-workflow.order.eline.delete
  endpoints:
    - id: delete connection by id
      path: ""
      method: ""
      serverKey: ""
      mappers:
        schemaRef:
          ref: "classpath:/mef-sonata/api-common-mappers/api-target-mapper.order.common.delete.yaml"
          params:
            - key: productType
              val: eline
        request:
        response: