
---
kind: kraken.component.api-target-mapper
apiVersion: v1
metadata:
  key: mef.sonata.api-target-mapper.order.uni.add
  name: Mapper Of Creating Order Port
  description: This operation creates a ProductOrder entity
  version: 3
spec:
  trigger:
    path: /mefApi/sonata/productOrderingManagement/v10/productOrder
    method: post
    productType: uni
    actionType: add
  supportedCase:
    type: ONE_TO_ONE_AND_ONE_TO_MANY
  workflow:
    enabled: false
    synchronous: false
    key: mef.sonata.api-workflow.order.uni.add
  endpoints:
    - id: create port order
      path: ""
      method: ""
      serverKey: ""
      mappers:
        schemaRef:
          ref: "classpath:/mef-sonata/api-common-mappers/api-target-mapper.order.common.add.yaml"
          params:
            - key: productType
              val: uni
        request:
          - name: mapper.order.uni.add.place.id
            title: >-
              the id of the place where the products' installation must be done.
            source: '@{{productOrderItem[0].product.place[0].id}}'
            description: ''
            sourceLocation: BODY
            sourceType: string
            target: ''
            targetLocation: BODY
            requiredMapping: false
        response: