---
kind: kraken.component.api-target-mapper
apiVersion: v1
metadata:
  key: mef.sonata.api-target-mapper.quote.uni.add.sync
  name: Mapper Of Creating Quote UNI
  description: This operation creates a Quote entity
  version: 3
spec:
  trigger:
    path: /mefApi/sonata/quoteManagement/v8/quote
    method: post
    productType: uni
    actionType: add
    quoteLevel: firm
    syncMode: true
  endpoints:
    - id: create quote for port
      path: ""
      method: ""
      serverKey: ""
      mappers:
        request:
          - name: mapper.quote.uni.add.sync.duration.amount
            title: "quote item Term duration"
            source: "@{{quoteItem[0].requestedQuoteItemTerm.duration.amount}}"
            sourceLocation: BODY
            target: ""
            targetLocation: BODY
            requiredMapping: true
          - name: mapper.quote.uni.add.sync.duration.units
            title: "quote item Term unit"
            source: "@{{quoteItem[0].requestedQuoteItemTerm.duration.units}}"
            sourceLocation: BODY
            sourceType: enum
            sourceValues:
              - calendarYears
              - calendarMonths
              - calendarDays
              - calendarHours
              - calendarMinutes
              - businessDays
              - businessHours
              - businessMinutes
            valueMapping: {}
            target: ""
            targetLocation: BODY
            requiredMapping: true
          - name: mapper.quote.uni.add.sync.endOfTermAction
            title: "MEFEndOfTermAction"
            source: "@{{quoteItem[0].requestedQuoteItemTerm.endOfTermAction}}"
            sourceLocation: BODY
            sourceType: enum
            sourceValues:
              - roll
              - autoDisconnect
              - autoRenew
            valueMapping: {}
            target: ""
            targetLocation: BODY
            requiredMapping: true
          - name: mapper.quote.uni.add.sync.rollInterval.amount
            title: "quote item Term roll duration"
            source: "@{{quoteItem[0].requestedQuoteItemTerm.rollInterval.amount}}"
            sourceLocation: BODY
            target: ""
            targetLocation: BODY
            requiredMapping: false
          - name: mapper.quote.uni.add.sync.rollInterval.units
            title: "quote item Term roll unit"
            source: "@{{quoteItem[0].requestedQuoteItemTerm.rollInterval.units}}"
            sourceLocation: BODY
            sourceType: enum
            sourceValues:
              - calendarYears
              - calendarMonths
              - calendarDays
              - calendarHours
              - calendarMinutes
              - businessDays
              - businessHours
              - businessMinutes
            valueMapping: {}
            target: ""
            targetLocation: BODY
            requiredMapping: false
          - name: mapper.quote.uni.add.sync.place.id
            title: "the id of the place where the products' quotation must be done"
            source: "@{{quoteItem[0].product.place[0].id}}"
            sourceLocation: BODY
            target: ""
            targetLocation: BODY
            requiredMapping: true
          - name: mapper.quote.uni.add.sync.productConfiguration.bandwidth
            title: "Bandwidth of the UNI"
            source: "@{{quoteItem[0].product.productConfiguration.bandwidth}}"
            sourceLocation: BODY
            target: ""
            targetLocation: BODY
            requiredMapping: true
          - name: mapper.quote.uni.add.sync.productConfiguration.bandwidthUnit
            title: "The unit of bandwidth"
            source: "@{{quoteItem[0].product.productConfiguration.bandwidthUnit}}"
            sourceLocation: BODY
            sourceType: enum
            sourceValues:
              - GBPS
              - MBPS
            valueMapping: {}
            target: ""
            targetLocation: BODY
            requiredMapping: true
          - name: mapper.quote.uni.add.sync.productOffering.id
            title: "The id of the quoted product offering"
            source: "@{{quoteItem[0].product.productOffering.id}}"
            sourceLocation: BODY
            target: ""
            targetLocation: BODY
            requiredMapping: false
        response:
          - name: mapper.quote.uni.add.sync.unitOfMeasure
            title: "Unit of Measure if price depending on it"
            description: ""
            source: ""
            sourceLocation: BODY
            target: "@{{quoteItem[0].quoteItemPrice[*].unitOfMeasure}}"
            targetLocation: BODY
            requiredMapping: false
          - name: mapper.quote.uni.add.sync.price.unit
            title: "Currency (ISO4217 norm uses 3 letters to define the currency)"
            description: ""
            source: ""
            sourceLocation: BODY
            target: "@{{quoteItem[0].quoteItemPrice[*].price.dutyFreeAmount.unit}}"
            targetLocation: BODY
            requiredMapping: true
          - name: mapper.quote.uni.add.sync.price.value
            title: "Duty free price value"
            description: ""
            source: ""
            sourceLocation: BODY
            target: "@{{quoteItem[0].quoteItemPrice[*].price.dutyFreeAmount.value}}"
            targetLocation: BODY
            requiredMapping: true
            checkPath: "$['quoteItem'][0]['quoteItemPrice'][0]['price']['dutyFreeAmount']['unit']"
            deletePath: "$['quoteItem'][0]['quoteItemPrice']"
          - name: mapper.quote.uni.add.sync.taxRate
            title: "Price Tax Rate. Unit: [%]. E.g. value 16 stand for 16% tax"
            description: ""
            source: ""
            sourceLocation: BODY
            target: "@{{quoteItem[0].quoteItemPrice[*].price.taxRate}}"
            targetLocation: BODY
            requiredMapping: false
          - name: mapper.quote.uni.add.sync.taxIncludedAmount.unit
            title: "Currency (ISO4217 norm uses 3 letters to define the currency)"
            description: ""
            source: ""
            sourceLocation: BODY
            target: "@{{quoteItem[0].quoteItemPrice[*].price.taxIncludedAmount.unit}}"
            targetLocation: BODY
            requiredMapping: false
          - name: mapper.quote.uni.add.sync.taxIncludedAmount.value
            title: "Tax included price value"
            description: ""
            source: ""
            sourceLocation: BODY
            target: "@{{quoteItem[0].quoteItemPrice[*].price.taxIncludedAmount.value}}"
            targetLocation: BODY
            requiredMapping: false
          - name: mapper.quote.uni.add.sync.quoteItemPrice.name
            title: "Name of the quote item price"
            description: ""
            source: ""
            sourceLocation: BODY
            target: "@{{quoteItem[0].quoteItemPrice[*].name}}"
            targetLocation: BODY
            requiredMapping: false
          - name: mapper.quote.uni.add.sync.quoteItemPrice.priceType
            title: "Indicates if the price is for recurring or non-recurring charges"
            description: ""
            source: ""
            sourceLocation: BODY
            target: "@{{quoteItem[0].quoteItemPrice[*].priceType}}"
            targetType: enum
            targetLocation: BODY
            requiredMapping: false
            targetValues:
              - recurring
              - nonRecurring
              - usageBased
            valueMapping: {}
          - name: mapper.quote.uni.add.sync.quoteItemPrice.description
            title: "Description of the quote item price"
            description: ""
            source: ""
            sourceLocation: BODY
            target: "@{{quoteItem[0].quoteItemPrice[*].description}}"
            targetLocation: BODY
            requiredMapping: false
          - name: mapper.quote.uni.add.sync.quoteItemPrice.recurringChargePeriod
            title: "Used for a recurring charge to indicate period"
            description: ""
            source: ""
            sourceLocation: BODY
            target: "@{{quoteItem[0].quoteItemPrice[*].recurringChargePeriod}}"
            targetType: enum
            targetLocation: BODY
            requiredMapping: false
            targetValues:
              - hour
              - day
              - week
              - month
              - year
            valueMapping: {}