---
kind: kraken.component.api-target-mapper
apiVersion: v1
metadata:
  key: mef.sonata.api-target-mapper.quote.eline.add.sync
  name: Mapper Of Creating Quote Eline
  description: This operation creates a Quote entity
  version: 4
spec:
  trigger:
    path: /mefApi/sonata/quoteManagement/v8/quote
    method: post
    productType: access_e_line
    actionType: add
    quoteLevel: firm
    syncMode: true
  endpoints:
    - id: create quote for connection
      path: /api/pricing/calculate
      method: post
      serverKey:
      mappers:
        pathRules:
          - name: mapper.quite.eline.add.sync.pathRule.state
            checkPath: "$[?(@.state != 'unableToProvide')]"
            deletePath: "$.validFor"
            insertPath:
              - key: "$.quoteItem[0].terminationError.code"
                val: "otherIssue"
              - key: "$.quoteItem[0].terminationError.value"
                val: "the quoted item is not available"
        schemaRef:
          ref: "classpath:/mef-sonata/api-common-mappers/api-target-mapper.quote.common.add.sync.yaml"
          params:
            - key: productType
              val: eline
        request:
          - name: mapper.quote.eline.add.sync.place1.id
            title: "The id of the place where destination location of the quoted product"
            source: "@{{quoteItem[0].product.place[1].id}}"
            sourceLocation: BODY
            sourceType: string
            target: ""
            targetLocation: BODY
            requiredMapping: true
          - name: mapper.quote.eline.add.sync.productConfiguration.classOfService
            title: "The class of Service of the E-Line"
            source: "@{{quoteItem[0].product.productConfiguration.classOfService}}"
            sourceLocation: BODY
            sourceType: string
            target: ""
            targetLocation: BODY
            requiredMapping: false
          - name: mapper.quote.eline.add.sync.productConfiguration.paymentType
            title: "The payment type of the E-Line"
            source: "@{{quoteItem[0].product.productConfiguration.paymentType}}"
            sourceLocation: BODY
            sourceType: string
            target: ""
            targetLocation: BODY
            requiredMapping: false
        response: