
---
kind: kraken.component.api-target-mapper
apiVersion: v1
metadata:
  key: mef.sonata.api-target-mapper.order.uni.add
  name: Mapper Of Creating Order Port
  description: This operation creates a ProductOrder entity
  version: 3
spec:
  trigger:
    path: /mefApi/sonata/productOrderingManagement/v10/productOrder
    method: post
    productType: uni
    actionType: add
  supportedCase:
    type: ONE_TO_ONE_AND_ONE_TO_MANY
  workflow:
    enabled: false
    synchronous: false
    key: mef.sonata.api-workflow.order.uni.add
  endpoints:
    - id: create port order
      path: ""
      method: ""
      serverKey: ""
      mappers:
        request:
          - name: mapper.order.uni.add.buyerId
            title: >-
              The unique identifier of the organization that is acting as the a
              Buyer.
            description: ""
            source: '@{{buyerId}}'
            sourceLocation: QUERY
            target: ""
            targetLocation: ""
            requiredMapping: false
          - name: mapper.order.uni.add.duration
            title: "order item Term duration"
            source: "@{{productOrderItem[0].requestedItemTerm.duration.amount}}"
            sourceType: integer
            sourceLocation: BODY
            discrete: true
            target: ""
            targetLocation: ""
            requiredMapping: true
          - name: mapper.order.uni.add.duration.units
            title: "order item Term unit"
            source: "@{{productOrderItem[0].requestedItemTerm.duration.units}}"
            sourceType: enum
            sourceLocation: BODY
            sourceValues:
              - calendarYears
              - calendarMonths
              - calendarDays
              - calendarHours
              - calendarMinutes
              - businessDays
              - businessHours
              - businessMinutes
            systemValueLimit: true
            target: ""
            targetLocation: BODY
            valueMapping: {}
            requiredMapping: true
          - name: mapper.order.eline.add.endOfTermAction
            title: "MEFEndOfTermAction"
            source: "@{{productOrderItem[0].requestedItemTerm.endOfTermAction}}"
            sourceType: string
            sourceLocation: BODY
            target: ""
            targetLocation: BODY
            requiredMapping: true
          - name: mapper.order.uni.add.rollInterval.amount
            title: " quote item Term roll duration"
            source: "@{{productOrderItem[0].requestedItemTerm.rollInterval.amount}}"
            sourceType: integer
            sourceLocation: BODY
            discrete: true
            sourceConditionExpression:
            sourceConditions:
              - name: endOfTermAction
                key: "@{{productOrderItem[0].requestedItemTerm.endOfTermAction}}"
                val: roll
                operator: eq
            target: ""
            targetLocation: BODY
            requiredMapping: false
          - name: mapper.order.uni.add.rollInterval.units
            title: " quote item Term roll unit"
            source: "@{{productOrderItem[0].requestedItemTerm.rollInterval.units}}"
            sourceType: enum
            sourceLocation: BODY
            sourceValues:
              - calendarYears
              - calendarMonths
              - calendarDays
              - calendarHours
              - calendarMinutes
              - businessDays
              - businessHours
              - businessMinutes
            systemValueLimit: true
            sourceConditionExpression:
            sourceConditions:
              - name: endOfTermAction
                key: "@{{productOrderItem[0].requestedItemTerm.endOfTermAction}}"
                val: roll
                operator: eq
            target: ""
            targetLocation: BODY
            requiredMapping: false
          - name: mapper.order.uni.add.place.id
            title: >-
              the id of the place where the products' installation must be done.
            description: ''
            source: '@{{productOrderItem[0].product.place[0].id}}'
            sourceType: string
            sourceLocation: BODY
            target: ''
            targetLocation: BODY
            requiredMapping: false
          - name: mapper.order.uni.add.bandwidthUnit
            title: "The unit of bandwidth"
            source: "@{{productOrderItem[0].product.productConfiguration.bandwidthUnit}}"
            sourceType: enum
            sourceLocation: BODY
            sourceValues:
              - MBPS
              - GBPS
            systemValueLimit: true
            target: ""
            targetLocation: BODY
            requiredMapping: true
          - name: mapper.order.uni.add.bandwidth
            title: "Bandwidth of the UNI"
            source: "@{{productOrderItem[0].product.productConfiguration.bandwidth}}"
            sourceType: integer
            sourceLocation: BODY
            sourceValues:
            allowValueLimit: true
            discrete: true
            systemValueLimit: true
            target: ""
            targetLocation: BODY
            requiredMapping: true
          - name: mapper.order.uni.add.name
            title: "The name of the UNI"
            source: "@{{productOrderItem[0].product.productConfiguration.name}}"
            sourceType: string
            sourceLocation: BODY
            target: ""
            targetLocation: BODY
            requiredMapping: false
          - name: mapper.order.uni.add.paymentType
            title: "The payment type of the UNI"
            source: "@{{productOrderItem[0].product.productConfiguration.paymentType}}"
            sourceType: string
            sourceLocation: BODY
            target: ""
            targetLocation: BODY
            requiredMapping: false
          - name: mapper.order.uni.add.productOffering.id
            title: "id of a Product Offering"
            source: "@{{productOrderItem[0].product.productOffering.id}}"
            sourceLocation: BODY
            target: ""
            targetLocation: BODY
            requiredMapping: true
        response:
          - name: mapper.order.uni.add.state
            title: Order State
            source: ""
            target: '@{{state}}'
            targetType: enum
            description: ''
            targetValues:
              - acknowledged
              - assessingCancellation
              - held.assessingCharge
              - pending.assessingModification
              - cancelled
              - pendingCancellation
              - completed
              - failed
              - inProgress
              - partial
              - rejected
            valueMapping: {}
            sourceLocation: BODY
            targetLocation: BODY
            requiredMapping: true
          - name: mapper.order.uni.add.orderId
            title: order Id from seller
            source: ""
            target: '@{{orderId}}'
            description: orderId mapping
            sourceLocation: BODY
            targetLocation: BODY
            requiredMapping: true
          - name: mapper.order.uni.add.instanceId
            title: instance id from seller
            source: ""
            target: '@{{instanceId}}'
            description: order instanceId mapping
            sourceLocation: BODY
            targetLocation: BODY
            requiredMapping: false
          - name: mapper.order.uni.add.product.id
            title: product instance id
            description: ""
            source: ""
            sourceLocation: BODY
            target: "@{{productOrderItem[0].product.id}}"
            targetLocation: BODY
            customizedField: false
            requiredMapping: false
          - name: mapper.order.uni.add.term.endOfTermAction
            title: MEFEndOfTermAction
            description: ""
            source: ""
            sourceLocation: ""
            target: "@{{productOrderItem[0].itemTerm.endOfTermAction}}"
            targetLocation: BODY
            customizedField: false
            requiredMapping: true
          - name: mapper.order.uni.add.term.rollInterval.amount
            title: order item Term roll duration
            description: ""
            source: ""
            sourceLocation: ""
            target: "@{{productOrderItem[0].itemTerm.rollInterval.amount}}"
            targetLocation: BODY
            customizedField: false
            requiredMapping: false
          - name: mapper.order.uni.add.term.rollInterval.unit
            title: order item Term roll unit
            description: ""
            source: ""
            sourceLocation: ""
            target: "@{{productOrderItem[0].itemTerm.rollInterval.units}}"
            targetLocation: BODY
            customizedField: false
            requiredMapping: false
          - name: mapper.order.uni.add.term.name
            title: order item Term name
            description: ""
            source: ""
            sourceLocation: ""
            target: "@{{productOrderItem[0].itemTerm.name}}"
            targetLocation: BODY
            customizedField: false
            requiredMapping: true