---
kind: kraken.component.api-target-mapper
apiVersion: v1
metadata:
  key: mef.sonata.api-target-mapper.inventory.uni.list
  name: Inventory Port API List
  description: This operation retrieves a list of product inventory
  version: 2
spec:
  inputs:
    - mefQuery
    - mefRequestBody
    - entity
  trigger:
    path: /mefApi/sonata/productInventory/v7/product
    method: get
    productType: uni
  endpoints:
    - id: list uni product
      path: ""
      method: ""
      mappers:
        schemaRef:
          ref: "classpath:/mef-sonata/api-common-mappers/api-target-mapper.inventory.common.list.yaml"
          params:
            - key: productType
              val: uni
        request:
        response: