---
kind: kraken.component.api-target-mapper
apiVersion: v1
metadata:
  key: mef.sonata.api-target-mapper.quote.uni.add
  name: Mapper Of Creating Quote UNI
  description: This operation creates a Quote entity
  version: 6
spec:
  trigger:
    path: /mefApi/sonata/quoteManagement/v8/quote
    method: post
    productType: uni
    actionType: add
    quoteLevel: firm
    syncMode: false
  endpoints:
    - id: create quote for port
      path: ""
      method: ""
      serverKey: ""
      mappers:
        request:
        response:
          - name: mapper.quote.uni.add.state
            title: Quote State Mapping
            description: quote state mapping
            source: ""
            sourceLocation: ""
            target: "@{{quoteItem[*].state}}"
            targetType: enum
            targetLocation: BODY
            requiredMapping: true
            targetValues:
              - accepted
              - acknowledged
              - answered
              - approved.orderable
              - approved.orderableAlternate
              - inProgress
              - inProgress.draft
              - abandoned
              - rejected
              - unableToProvide
            valueMapping: {}
          - name: mapper.quote.uni.add.price.value
            title: Quote Price Value Mapping
            description: quote price mapping
            source: ""
            sourceLocation: ""
            target: "@{{quoteItem[0].quoteItemPrice[*].price.dutyFreeAmount.value}}"
            targetLocation: BODY
            requiredMapping: true
          - name: mapper.quote.uni.add.price.unit
            title: Quote Price Unit Mapping
            description: quote price mapping
            source: ""
            sourceLocation: ""
            target: "@{{quoteItem[0].quoteItemPrice[*].price.dutyFreeAmount.unit}}"
            targetLocation: BODY
            requiredMapping: true
