---
kind: kraken.component.api-target-mapper
apiVersion: v1
metadata:
  key: mef.sonata.api-target-mapper.order.uni.delete
  name: Mapper Of Deleting Order Port
  description: This operation deletes a ProductOrder entity
spec:
  trigger:
    path: /mefApi/sonata/productOrderingManagement/v10/productOrder
    method: post
    productType: uni
    actionType: delete
  endpoints:
    - id: delete port
      path: ""
      method: ""
      serverKey: mef.sonata.api-target-spec.con1718940696857
      mappers:
        request:
          - name: mapper.order.uni.delete.buyerId
            title: "The unique identifier of the organization that is acting as the a Buyer."
            description: ""
            source: "@{{buyerId}}"
            sourceLocation: "QUERY"
            target: ""
            targetLocation: ""
            requiredMapping: false
          - name: mapper.order.uni.delete.productId
            title: "The unique identifier of an in-service Product that is the ordering subject"
            description: ""
            source: "@{{productOrderItem[*].product.id}}"
            sourceLocation: "BODY"
            target: ""
            targetLocation: ""
            requiredMapping: false
        response:
          - name: mapper.order.uni.delete.state
            title: Order State Mapping
            description: order state mapping
            target: "@{{state}}"
            targetType: enum
            targetLocation: BODY
            targetValues:
              - acknowledged
              - assessingCancellation
              - held.assessingCharge
              - pending.assessingModification
              - cancelled
              - pendingCancellation
              - completed
              - failed
              - inProgress
              - partial
              - rejected
            valueMapping: {}
            source: ""
            sourceLocation: ""