---
kind: kraken.component.api-target-mapper
apiVersion: v1
metadata:
  key: mef.sonata.api-target-mapper.order.eline.read
  name:  Mapper Of Reading Order Connection
  description: This operation retrieves a ProductOrder entity
spec:
  trigger:
    path: /mefApi/sonata/productOrderingManagement/v10/productOrder/{id}
    method: get
    productType: access_e_line
  endpoints:
    - path: ""
      method: ""
      serverKey: mef.sonata.api-target-spec.con1718940696857
      mappers:
        request:
        response:
          - name: mapper.order.eline.read.state
            title: Order State Mapping
            description: order state mapping
            target: "@{{state}}"
            targetType: enum
            targetLocation: BODY
            targetValues:
              - acknowledged
              - assessingCancellation
              - held.assessingCharge
              - pending.assessingModification
              - cancelled
              - pendingCancellation
              - completed
              - failed
              - inProgress
              - partial
              - rejected
            valueMapping: {}
            source: ""
            sourceLocation: ""
