---
kind: kraken.component.api-target-mapper
apiVersion: v1
metadata:
  key: mef.sonata.api-target-mapper.poq.eline.add
  name: Product Offering Qualification (POQ) API
  description: | 
    A request initiated by the Buyer to determine whether the Seller is
    able to deliver a product or set of products from among their product
    offerings, at the Buyer's location(s); or modify a previously purchased
    product. The Seller also provides estimated time intervals to complete
    these deliveries. Reference: MEF 79 (Sn 8.4).
spec:
  trigger:
    path: /mefApi/sonata/productOfferingQualification/v7/productOfferingQualification
    method: post
    productType: access_e_line
    actionType: add
  endpoints:
    - id: create a product offering qualification for connection
      path: /api/pricing/calculate
      method: post
      serverKey: mef.sonata.api-target-spec.con1718940696857
      mappers:
        request:
        response:
          - name: mapper.poq.eline.add.itemState
            title: POQ Item State Mapping
            description: POQ Item state mapping
            source: ""
            sourceLocation: ""
            target: "@{{itemState}}"
            targetType: enum
            targetLocation: BODY
            targetValues:
              - acknowledged
              - done.ready
              - done.abandoned
              - terminatedWithError
              - approved.orderableAlternate
              - inProgress
            valueMapping: {}
            defaultValue: "done.ready"
            requiredMapping: false
          - name: mapper.poq.eline.add.state
            title: POQ State Mapping
            description: POQ state mapping
            source: ""
            sourceLocation: ""
            target: "@{{state}}"
            targetType: enum
            targetLocation: BODY
            targetValues:
              - acknowledged
              - done.ready
              - done.unableToProvide
              - terminatedWithError
              - approved.orderableAlternate
              - inProgress
            valueMapping: {}
            defaultValue: "done.ready"
            requiredMapping: false