---
kind: kraken.product.app.kraken
apiVersion: v1
metadata:
  key: kraken@1.2.0-SNAPSHOT
  name: Kraken App 1.2.0-SNAPSHOT
  labels:
    productSpec: grace
    productVersion: V1.5.4
    appVersion: 1.2.0-SNAPSHOT
    publishDate: 2024-11-06
    productKey: mef.sonata
  version: 1
spec:
  use-cases:
    - name: Product Ordering Management
      key: mef.sonata.api.order
      apiVersion: v10
      endpoints:
        - path: /mefApi/sonata/productOrderingManagement/v10/productOrder
          method: post
          mapping-matrix:
            productType: access_e_line
            actionType: add
        - path: /mefApi/sonata/productOrderingManagement/v10/productOrder
          method: post
          mapping-matrix:
            productType: uni
            actionType: add
        - path: /mefApi/sonata/productOrderingManagement/v10/productOrder/{id}
          method: get
          mapping-matrix:
            productType: access_e_line
        - path: /mefApi/sonata/productOrderingManagement/v10/productOrder/{id}
          method: get
          mapping-matrix:
            productType: uni
        - path: /mefApi/sonata/productOrderingManagement/v10/productOrder
          method: post
          mapping-matrix:
            productType: access_e_line
            actionType: delete
        - path: /mefApi/sonata/productOrderingManagement/v10/productOrder
          method: post
          mapping-matrix:
            productType: uni
            actionType: delete
    - name: Quote Management
      key: mef.sonata.api.quote
      apiVersion: v8
      endpoints:
        - path: /mefApi/sonata/quoteManagement/v8/quote
          method: post
          mapping-matrix:
            productType: access_e_line
            actionType: add
            quoteLevel: firm
            syncMode: true
        - path: /mefApi/sonata/quoteManagement/v8/quote
          method: post
          mapping-matrix:
            productType: uni
            actionType: add
            quoteLevel: firm
            syncMode: true
        - path: /mefApi/sonata/quoteManagement/v8/quote/{id}
          method: get
          mapping-matrix:
            productType: access_e_line
            quoteLevel: firm
            syncMode: true
        - path: /mefApi/sonata/quoteManagement/v8/quote/{id}
          method: get
          mapping-matrix:
            productType: uni
            quoteLevel: firm
            syncMode: true
    - name: Product Inventory Management
      key: mef.sonata.api.inventory
      apiVersion: v7
      endpoints:
        - path: /mefApi/sonata/productInventory/v7/product
          method: get
          mapping-matrix:
            productType: access_e_line
        - path: /mefApi/sonata/productInventory/v7/product
          method: get
          mapping-matrix:
            productType: uni
        - path: /mefApi/sonata/productInventory/v7/product/{id}
          method: get
          mapping-matrix:
            productType: access_e_line
        - path: /mefApi/sonata/productInventory/v7/product/{id}
          method: get
          mapping-matrix:
            productType: uni
    - name: Geographic Address Management
      key: mef.sonata.api.address
      apiVersion: v7
      endpoints:
        - path: /mefApi/sonata/geographicAddressManagement/v7/geographicAddress/{id}
          method: get
          mapping-matrix:
            addressType: FieldedAddress
        - path: /mefApi/sonata/geographicAddressManagement/v7/geographicAddressValidation
          method: post
          mapping-matrix:
            provideAlternative: false
            addressType: FieldedAddress