---
kind: kraken.product.template-upgrade
apiVersion: v1
metadata:
  key: kraken.product.template-upgrade.1.0.1
  name: V1.0.1
  labels:
    productSpec: grace
    productVersion: V1.0.1
    publishDate: 2025-02-18
  description: |
    Update mapper order uni read
    Add mapper matrix
  version: 2
