
---
kind: kraken.component.api-target
apiVersion: v1
metadata:
  key: mef.sonata.api-target.order.uni.add
  name: Order Port API
  mapperKey: mef.sonata.api-target-mapper.order.uni.add
  version: 4
spec:
  inputs:
    - mefQuery
    - mefRequestBody
  trigger:
    path: /mefApi/sonata/productOrderingManagement/v10/productOrder
    method: post
    productType: uni
    actionType: add
  endpoints:
    - id: create port order
      path: ""
      method: ""
      requestBody: ${mefRequestBody.productOrderItem[0].product.productConfiguration.uni}
      responseBody: |
        {
          "relatedContactInformation": "${T(com.consoleconnect.kraken.operator.gateway.func.SpelFunc).appendSellerInformation(env.seller.role, env.seller.name, env.seller.emailAddress, env.seller.number, mefRequestBody.relatedContactInformation)}",
         "id": "${entity.id}",
         "orderDate":"${T(com.consoleconnect.kraken.operator.core.toolkit.DateTime).nowInUTCFormatted()}",
         "productOrderItem": "${mefRequestBody.productOrderItem}",
         "state": "@{{state}}",
         "orderId": "@{{orderId}}",
         "instanceId": "@{{instanceId}}"
        }