---
kind: kraken.component.api-target
apiVersion: v1
metadata:
  key: mef.sonata.api-target.inventory.uni.read
  mapperKey: mef.sonata.api-target-mapper.inventory.uni.read
  name: Product Inventory UNI
  version: 7
spec:
  inputs:
    - mefQuery
  trigger:
    path: /mefApi/sonata/productInventory/v7/product/{id}
    method: get
    productType: uni
  endpoints:
    - id: Retrieves a product by ID
      path: ""
      method: ""
      responseBody: |
        { 
          "id": "${segment}",
          "startDate": "",
          "status": "",
          "productOrderItem":[
            {
              "productOrderHref":"",
              "productOrderItemId":"${entity.renderedResponse.productOrderItem[0]['id']}",
              "productOrderId":"${entity.renderedResponse['id']}"
            }
          ],
          "relatedSite":[
            {
              "role":"${entity.renderedResponse.productOrderItem[0].product.place[0].role}",
              "id":"${entity.renderedResponse.productOrderItem[0].product.place[0].id}",
              "href":""
            }
          ],
          "productOffering":{
            "href":"",
            "id":"${entity.renderedResponse.productOrderItem[0].product.productOffering.id}"
          },
          "productTerm":[{
              "duration":"${entity.renderedResponse.productOrderItem[0].requestedItemTerm.duration}",
              "endOfTermAction":"${entity.renderedResponse.productOrderItem[0].requestedItemTerm.endOfTermAction}",
              "name":"${entity.renderedResponse.productOrderItem[0].requestedItemTerm.name}",
              "rollInterval":"${entity.renderedResponse.productOrderItem[0].requestedItemTerm.rollInterval}"
            }
          ],
          "productRelationship":"${entity.renderedResponse.productOrderItem[0].product.productRelationship}",
          "productConfiguration": {
            "name": "${entity.renderedResponse.productOrderItem[0].product.productConfiguration.name}",
            "@type":"${entity.renderedResponse.productOrderItem[0].product.productConfiguration['@type']?:''}",
            "bandwidth":"${entity.renderedResponse.productOrderItem[0].product.productConfiguration.bandwidth}",
            "paymentType":"${entity.renderedResponse.productOrderItem[0].product.productConfiguration.paymentType}",
            "bandwidthUnit":"${entity.renderedResponse.productOrderItem[0].product.productConfiguration[bandwidthUnit]?:''}",
            "buyerCompanyId":"${entity.renderedResponse.productOrderItem[0].product.productConfiguration[buyerCompanyId]?:''}",
            "classOfService":"${entity.renderedResponse.productOrderItem[0].product.productConfiguration[classOfService]?:''}",
            "destUNIMetroId":"${entity.renderedResponse.productOrderItem[0].product.productConfiguration[destUNIMetroId]?:''}"
          }
        }