---
kind: kraken.component.api-target
apiVersion: v1
metadata:
  key: mef.sonata.api-target.quote.uni.add.sync
  name: Quote Management API
  mapperKey: mef.sonata.api-target-mapper.quote.uni.add.sync
  version: 4
spec:
  inputs:
    - mefQuery
    - mefRequestBody
    - entity
  trigger:
    path: /mefApi/sonata/quoteManagement/v8/quote
    method: post
    productType: uni
    actionType: add
    sellerContactKeys:
      - mef.sonata.api.quote.access.eline
  endpoints:
    - id: create quote for port
      path:
      method:
      requestBody: |
        {}
      responseBody: |
        {
          "id": "${entity.id}",
          "buyerRequestedQuoteLevel": "${mefRequestBody.buyerRequestedQuoteLevel}",
          "relatedContactInformation": "${T(com.consoleconnect.kraken.operator.gateway.func.SpelFunc).appendSellerInformation('sellerContactInformation', env.seller.name, env.seller.emailAddress, env.seller.number, mefRequestBody[relatedContactInformation]?:'')}",
          "quoteItem": [
            {
              "requestedQuoteItemTerm": "${mefRequestBody.quoteItem[0].requestedQuoteItemTerm}",
              "product": "${mefRequestBody.quoteItem[0].product}",
              "action": "add",
              "id": "${mefRequestBody.quoteItem[0].id}",
              "state": "(((mefResponseBody.quoteItem[0].quoteItemPrice[0].price.dutyFreeAmount.value == '') or (T(java.lang.Double).parseDouble(mefResponseBody.quoteItem[0].quoteItemPrice[0].price.dutyFreeAmount.value) < 0)? 'unableToProvide': 'approved.orderable'))",
              "quoteItemTerm": "${T(java.util.Arrays).asList(mefRequestBody.quoteItem[0].requestedQuoteItemTerm)}",
              "quoteItemPrice": [{
                "unitOfMeasure":"",
                "price": {
                  "dutyFreeAmount": {
                     "unit": "",
                     "value": ""
                  },
                  "taxRate":"",
                  "taxIncludedAmount": {
                    "unit": "",
                    "value": ""
                  }
                },
                "name":"",
                "priceType":"",
                "description":"",
                "recurringChargePeriod":""
              }]
            }
          ],
          "quoteDate": "${T(com.consoleconnect.kraken.operator.core.toolkit.DateTime).nowInUTCFormatted()}",
          "externalId":"${mefRequestBody[externalId]?:''}",
          "instantSyncQuote":"${mefRequestBody[instantSyncQuote]?:''}",
          "requestedQuoteCompletionDate": "${mefRequestBody[requestedQuoteCompletionDate]?:''}",
          "quoteLevel": "${mefRequestBody.buyerRequestedQuoteLevel}",
          "state": "(((mefResponseBody.quoteItem[0].quoteItemPrice[0].price.dutyFreeAmount.value == '') or (T(java.lang.Double).parseDouble(mefResponseBody.quoteItem[0].quoteItemPrice[0].price.dutyFreeAmount.value) < 0)? 'unableToProvide': 'approved.orderable'))"
        }