---
kind: kraken.component.api-target
apiVersion: v1
metadata:
  key: mef.sonata.api-target.inventory.uni.read
  mapperKey: mef.sonata.api-target-mapper.inventory.uni.read
  name: Product Inventory UNI
  version: 7
spec:
  inputs:
    - mefQuery
  trigger:
    path: /mefApi/sonata/productInventory/v7/product/{id}
    method: get
    productType: uni
  endpoints:
    - id: Retrieves a product by ID
      path: ""
      method: ""
      responseBody: |
        { 
          "id": "${segment}",
          "startDate": "@{{startDate}}",
           "status": "@{{status}}"
        }