---
kind: kraken.component.api-target
apiVersion: v1
metadata:
  key: mef.sonata.api-target.inventory.uni.list
  name: Inventory Connection API
  mapperKey: mef.sonata.api-target-mapper.inventory.uni.list
  version: 2
spec:
  inputs:
    - mefQuery
    - mefRequestBody
    - entity
  trigger:
    path: /mefApi/sonata/productInventory/v7/product
    method: get
    productType: uni
  endpoints:
    - id: list uni product
      pathReferId: "mef.sonata.api-target-mapper.order.uni.add#mapper.order.uni.add.orderId"
      responseBody: |
        [
          {
            "id": "",
            "startDate": "",
            "status": "",
            "productSpecification":{},
            "relatedSite":[],
            "productOffering":"${entity.request.productOrderItem[0].product.productOffering}",
            "lastUpdateDate":"",
            "externalId":"${entity.request[externalId]?:''}",
            "productRelationship":"${entity.request.productOrderItem[0].product.productRelationship}",
            "billingAccount":"${entity.request.productOrderItem[0].billingAccount}",
            "productOrderItem":[
              {
                "productOrderHref":"",
                "productOrderItemId":"${entity.renderedResponse.productOrderItem[0]['id']}",
                "productOrderId":"${entity.renderedResponse['orderId']}"
              }
            ]
          }
        ]