---
kind: kraken.product.mapping.matrix
apiVersion: v1
metadata:
  key: mef.sonata.api.matrix.quote.eline.add.sync
  name: MEF Sonata API
  labels:
    mef-api-release: grace
  version: 14
spec:
  expect-http-status-422-if-missing:
    - $.body.quoteItem[0].product.productConfiguration
  matrix:
    mef.sonata.api-target.quote.eline.add.sync:
      - name: action_add
        path: "$.body.quoteItem[*].['action']"
        expectType: EXPECTED
        value: add
        code: 400
      - name: syn_mode_true
        path: "$.body.instantSyncQuote"
        expectType: EXPECTED
        value: true
      - name: buyer.requested.quote.level.firm
        path: "$.body.buyerRequestedQuoteLevel"
        expectType: EXPECTED
        value: firm
      - name: quoteItem[0].product.place[0].role
        path: "$.body.quoteItem[0].product.place[0].role"
        expectType: EXPECTED
        value: INSTALL_LOCATION
      - name: quoteItem[0].product.place[1].role
        path: "$.body.quoteItem[0].product.place[1].role"
        expectType: EXPECTED
        value: INSTALL_LOCATION
      - name: quoteItem[0].product.place[0].@type
        path: "$.body.quoteItem[0].product.place[0].@type"
        expectType: EXPECTED_STR
        value: true
        code: 422
      - name: quoteItem[0].product.place[1].@type
        path: "$.body.quoteItem[0].product.place[1].@type"
        expectType: EXPECTED_STR
        value: true
        code: 422
      - name: product_type_eline
        path: "$.body.quoteItem[0].product.productConfiguration.['@type']"
        expectType: EXPECTED
        value: ACCESS_E_LINE
      - name: relationship_type_0
        path: "$.body.quoteItem[0].product.productRelationship[0].['relationshipType']"
        expectType: EXPECTED
        value: CONNECTS_TO_ENNI
      - name: relationship_type_1
        path: "$.body.quoteItem[0].product.productRelationship[1].['relationshipType']"
        expectType: EXPECTED
        value: CONNECTS_TO_UNI
      - name: relationship_0_id
        path: "$.body.quoteItem[0].product.productRelationship[0].['id']"
        expectType: EXPECTED_STR
        value: true
        code: 422
      - name: relationship_1_id
        path: "$.body.quoteItem[0].product.productRelationship[1].['id']"
        expectType: EXPECTED_STR
        value: true
        code: 422