---
server:
  port: 8080
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://db-data-plane:5432/kraken
    username: postgresql
    password: password
app:
  controlPlane:
    url: http://kraken-app-controller:8080
    auth:
      authMode: internalToken
      internalToken:
        accessToken: ${CONTROL_PLANE_TOKEN}