---
server:
  port: 8080
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://db-data-plane:5432/kraken
    username: postgresql
    password: password

app:
  cron-job:
    push-heartbeat: 0/20 * * * * *

