---
kind: kraken.product.mapping.matrix
apiVersion: v1
metadata:
  key: mef.sonata.api.matrix.quote.eline.add
  name: MEF Sonata API
  labels:
    mef-api-release: grace
  version: 14
spec:
  matrix:
    mef.sonata.api-target.quote.eline.add:
      - name: enabled
        expectType: EXPECTED
        value: false
        errorMsg: "api use case is not supported : disabled : instantSyncQuote==false"
      - name: product_type_eline
        path: "$.body.quoteItem[*].product.productConfiguration.['@type']"
        expectType: EXPECTED
        value: ACCESS_E_LINE
      - name: action_add
        path: "$.body.quoteItem[*].['action']"
        expectType: EXPECTED
        value: add
      - name: syn_mode_false
        path: "$.body.instantSyncQuote"
        expectType: EXPECTED
        value: false
      - name: buyer.requested.quote.level.firm
        path: "$.body.buyerRequestedQuoteLevel"
        expectType: EXPECTED
        value: firm
