---
kind: kraken.product.mapping.matrix
apiVersion: v1
metadata:
  key: mef.sonata.api.matrix.order.uni.add
  name: MEF Sonata API
  labels:
    mef-api-release: grace
  version: 18
spec:
  matrix:
    mef.sonata.api-target.order.uni.add:
      - name: product_type_UNI
        path: "$.body.productOrderItem[*].product.productConfiguration.['@type']"
        expectType: EXPECTED
        value: UNI
      - name: action_add
        path: "$.body.productOrderItem[*].['action']"
        expectType: EXPECTED
        value: add
      - name: productOrderItem_product_place_role
        path: "$.body.productOrderItem[0].product.place[0].role"
        expectType: EXPECTED_EXIST
        value: true
      - name: productOrderItem_product_place_@type
        path: "$.body.productOrderItem[0].product.place[0].@type"
        expectType: EXPECTED_EXIST
        value: true
      - name: productOrderItem_product_place_@type_should_be
        path: "$.body.productOrderItem[0].product.place[0].@type"
        expectType: EXPECTED
        value: "GeographicAddressRef"
      - name: relatedContactInformation_emailAddress
        path: "$.body.relatedContactInformation[*]"
        expectType: EXPECTED_TRUE
        value: ${param.emailAddress}
        errorMsg: "relatedContactInformation.emailAddress should exist in request"
      - name: relatedContactInformation_name
        path: "$.body.relatedContactInformation[*]"
        expectType: EXPECTED_TRUE
        value: ${param.name}
        errorMsg: "relatedContactInformation.name should exist in request"
      - name: relatedContactInformation_number
        path: "$.body.relatedContactInformation[*]"
        expectType: EXPECTED_TRUE
        value: ${param.number}
        errorMsg: "relatedContactInformation.number should exist in request"
      - name: relatedContactInformation_role
        path: "$.body.relatedContactInformation[*]"
        expectType: EXPECTED_TRUE
        value: ${param.role}
        errorMsg: "relatedContactInformation.role should exist in request"
      - name: productOrderItem_id
        path: "$.body.productOrderItem[0].id"
        expectType: EXPECTED_EXIST
        value: true
        errorMsg: "productOrderItem.id should exist in request"
      - name: productOrderItem_requestedItemTerm_name
        path: "$.body.productOrderItem[0].requestedItemTerm.name"
        expectType: EXPECTED_EXIST
        value: true
