---
kind: kraken.product.mapping.matrix
apiVersion: v1
metadata:
  key: mef.sonata.api.matrix.poq.uni.add
  name: MEF Sonata API
  labels:
    mef-api-release: grace
  version: 1
spec:
  expect-http-status-422-if-missing:
    - $.body.productOfferingQualificationItem[0].product.productConfiguration
  matrix:
    mef.sonata.api-target.poq.uni.add:
      - name: syn_mode
        path: "$.body.instantSyncQualification"
        expectType: EXPECTED
        value: true
      - name: action_add
        path: "$.body.productOfferingQualificationItem[*].['action']"
        expectType: EXPECTED
        value: add
        code: 400
      - name: alternative_way
        path: "$.body.provideAlternative"
        expectType: EXPECTED
        value: false
      - name: productOfferingQualificationItem[0].id
        path: "$.body.productOfferingQualificationItem[0].id"
        expectType: EXPECTED_STR
        value: true
        code: 422
      - name: productOfferingQualificationItem[0].product.place[0].role
        path: "$.body.productOfferingQualificationItem[0].product.place[0].role"
        expectType: EXPECTED
        value: INSTALL_LOCATION
      - name: productOfferingQualificationItem[0].product.place[0].@type
        path: "$.body.productOfferingQualificationItem[0].product.place[0].@type"
        expectType: EXPECTED
        value: GeographicAddressRef, GeographicSiteRef
      - name: product_type_UNI
        path: "$.body.productOfferingQualificationItem[*].product.productConfiguration.['@type']"
        expectType: EXPECTED
        value: UNI