---
kind: kraken.product.mapping.matrix
apiVersion: v1
metadata:
  key: mef.sonata.api.matrix.order.eline.read
  name: MEF Sonata API
  labels:
    mef-api-release: grace
  version: 1
spec:
  matrix:
    mef.sonata.api-target.order.eline.read:
