---
kind: kraken.component.api-workflow
apiVersion: v1
metadata:
  key: mef.sonata.api-workflow.order.eline.add
  name: Order Management
  version: 1
spec:
  metaData:
    workflowName: "order.eline.add"
    externalId: ""
  validationMapper:
  validationStage:
    - taskName: validation_task
      description: ""
      taskType: ""
      endpoint:
        path: ""
        method: ""
        serverKey: ''
        mappers:
          request:
      conditionCheck:
        caseExpression: ""
        buildInTask: reject_order_task
  preparationStage:
    - taskName: preparation_task
      description: ""
      taskType: http
      endpoint:
        path: ""
        method: ""
        serverKey: ''
        mappers:
          request:
  executionStage:
    - taskName: create_order_task
      description: "create eline order task"
      taskType: http
      endpoint:
        path: ""
        method: ""
        serverKey: ""
        mappers:
          request:
          response:
            - name: mapper.order.eline.add.orderId
              title: order Id from seller
              source: ""
              target: '@{{orderId}}'
              description: ""
              sourceLocation: BODY
              targetLocation: BODY
              requiredMapping: true
      notificationUrl:
