---
kind: kraken.component.api-workflow
apiVersion: v1
metadata:
  key: mef.sonata.api-workflow.order.eline.delete
  name: Order Management
  version: 1
spec:
  metaData:
    workflowName: "order.eline.delete"
    externalId: ""
  validationStage:
    - taskName: status_checking_task
      taskType: http
      endpoint:
        path: "/api/v2/company/{username}/connections/{connectionId}"
        method: GET
        serverKey: ''
        mappers:
          request:
            - name: mapper.order.eline.delete.buyerId
              title: "The unique identifier of the organization that is acting as the a Buyer."
              description: ""
              source: "@{{buyerId}}"
              sourceLocation: "QUERY"
              target: "@{{username}}"
              targetLocation: "PATH"
              requiredMapping: false
            - name: mapper.order.eline.delete.productId
              title: "The unique identifier of an in-service Product that is the ordering subject"
              description: ""
              source: "@{{productOrderItem[*].product.id}}"
              sourceLocation: "BODY"
              target: "@{{connectionId}}"
              targetLocation: "PATH"
              requiredMapping: true
      conditionCheck:
        caseExpression: "${status_checking_task.output.response.body.state}==DELETED"
        buildInTask: reject_order_task
  preparationStage:
    - taskName: disable_order_task
      taskType: http
      endpoint:
        path: "/api/company/{username}/connections/{connectionId}/disable"
        method: PUT
        serverKey: ''
        mappers:
          request:
            - name: mapper.order.eline.delete.buyerId
              title: "The unique identifier of the organization that is acting as the a Buyer."
              description: ""
              source: "@{{buyerId}}"
              sourceLocation: "QUERY"
              target: "@{{username}}"
              targetLocation: "PATH"
              requiredMapping: false
            - name: mapper.order.eline.delete.productId
              title: "The unique identifier of an in-service Product that is the ordering subject"
              description: ""
              source: "@{{productOrderItem[*].product.id}}"
              sourceLocation: "BODY"
              target: "@{{connectionId}}"
              targetLocation: "PATH"
              requiredMapping: true
  executionStage:
    - taskName: delete_order_task
      taskType: http
      endpoint:
        path: "/api/v2/company/{username}/connections/{connectionId}"
        method: 'DELETE'
        serverKey: ''
        mappers:
          request:
            - name: mapper.order.eline.delete.buyerId
              title: "The unique identifier of the organization that is acting as the a Buyer."
              description: ""
              source: "@{{buyerId}}"
              sourceLocation: "QUERY"
              target: "@{{username}}"
              targetLocation: "PATH"
              requiredMapping: false
            - name: mapper.order.eline.delete.productId
              title: "The unique identifier of an in-service Product that is the ordering subject"
              description: ""
              source: "@{{productOrderItem[*].product.id}}"
              sourceLocation: "BODY"
              target: "@{{connectionId}}"
              targetLocation: "PATH"
              requiredMapping: true
      notificationUrl: http://slack.notice/api










