---
kind: kraken.product.template-upgrade
apiVersion: v1
metadata:
  key: kraken.product.template-upgrade.1.7.1
  name: V1.7.1
  labels:
    productSpec: grace
    productVersion: V1.7.1
    publishDate: 2025-01-07
  description: |
    Adding a property named 'allowValueLimit' to mark whether allowing customized value limitation.
  version: 1