---
kind: kraken.product.template-upgrade
apiVersion: v1
metadata:
  key: kraken.product.template-upgrade.1.8.0
  name: V1.8.0
  labels:
    productSpec: grace
    productVersion: V1.8.0
    publishDate: 2025-02-20
  description: |
    Fixed issues:
      - fix mef test case issues
    Improvements: 
      - performance improvement for activity log
      - performance improvement for api spec setup
  version: 1