---
kind: kraken.product.template-upgrade
apiVersion: v1
metadata:
  key: kraken.product.template-upgrade.1.7.44
  name: V1.7.44
  labels:
    productSpec: grace
    productVersion: V1.7.44
    publishDate: 2025-04-07
  description: |
    Add orderId in api target
  version: 1