---
kind: kraken.product.template-upgrade
apiVersion: v1
metadata:
  key: kraken.product.template-upgrade.1.6.3
  name: V1.6.3
  labels:
    productSpec: grace
    productVersion: V1.6.3
    publishDate: 2024-12-17
  description: |
    Add data type validation for the following use cases:
    - UNI order creating
    - Eline order creating
  version: 1