---
kind: kraken.product.template-upgrade
apiVersion: v1
metadata:
  key: kraken.product.template-upgrade.2.2.3
  name: V2.2.3
  labels:
    productSpec: grace
    productVersion: V2.2.3
    publishDate: 2025-12-19
  description: |
    Product of Quote order cases: 
     - Removed descriptions for poq request mapping items
  version: 1