---
kind: kraken.product.template-upgrade
apiVersion: v1
metadata:
  key: kraken.product.template-upgrade.1.7.18
  name: V1.7.18
  labels:
    productSpec: grace
    productVersion: V1.7.18
    publishDate: 2025-02-26
  description: |
    When the quote state is 'unableToProvide', remove the 'validFor' and 'quoteLevel' nodes, 
    insert the 'quoteItem[0].terminationError' node.
  version: 1