---
kind: kraken.product.template-upgrade
apiVersion: v1
metadata:
  key: kraken.product.template-upgrade.1.5.20
  name: V1.5.20
  labels:
    productSpec: grace
    productVersion: V1.5.20
    publishDate: 2024-11-21
  description: |
    Removed the constant value validation of 'place.@type' but remained the existence checking of this node.
  version: 2