---
kind: kraken.product.template-upgrade
apiVersion: v1
metadata:
  key: kraken.product.template-upgrade.1.7.38
  name: V1.7.38
  labels:
    productSpec: grace
    productVersion: V1.7.38
    publishDate: 2025-04-01
  description: |
    Split modify apis: 
      - create modify eline quote
      - create modify eline order
      - get modify eline order by id
  version: 1