---
kind: kraken.product.template-upgrade
apiVersion: v1
metadata:
  key: kraken.product.template-upgrade.1.7.23
  name: V1.7.23
  labels:
    productSpec: grace
    productVersion: V1.7.23
    publishDate: 2025-03-10
  description: |
    Added template labels for product offering qualification
  version: 1