---
kind: kraken.product.template-upgrade
apiVersion: v1
metadata:
  key: kraken.product.template-upgrade.1.7.27
  name: V1.7.27
  labels:
    productSpec: grace
    productVersion: V1.7.27
    publishDate: 2025-03-20
  description: |
    Added ref path for common template implementation
  version: 1