---
kind: kraken.product.template-upgrade
apiVersion: v1
metadata:
  key: kraken.product.template-upgrade.1.7.29
  name: V1.7.29
  labels:
    productSpec: grace
    productVersion: V1.7.29
    publishDate: 2025-03-21
  description: |
    Added support for state related issue in retrieve by id cases when using workflow
  version: 1