package com.consoleconnect.kraken.operator.core.client;

public enum ClientEventTypeEnum {
  CLIENT_API_AUDIT_LOG,
  CLIENT_HEARTBEAT,
  CLIENT_DEPLOYMENT,
  CLIENT_SERVER_API,
  CLIENT_TEMPLATE_UPGRADE_RESULT,
  CLIENT_SYSTEM_INFO,
  CLIENT_MAPPER_VERSION,
  CLIENT_APP_VERSION_UPGRADE_RESULT,
  CLIENT_PUSH_API_ACTIVITY_LOG
}
