---
name: Build docker images
on:
  workflow_dispatch:

jobs:
  container_build:
    name: Build docker images and publish to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Get the current version
        id: vars
        run: |
          git log -n 5

          COMMIT_HASH_SHORT=$(git rev-parse --short HEAD)
          echo $COMMIT_HASH_SHORT

          CURRENT_VERSION=$(./mvnw org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate -Dexpression=project.version -q -DforceStdout)
          echo $CURRENT_VERSION
          
          DOCKER_IMAGE_TAG=$CURRENT_VERSION-$COMMIT_HASH_SHORT
          echo "docker-image-tag=$DOCKER_IMAGE_TAG" >> $GITHUB_OUTPUT


      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build kraken-app-controller container
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/app-controller/Dockerfile
          push: true
          tags: cloudnexusopsdockerhub/kraken-app-controller:${{ steps.vars.outputs.docker-image-tag }}

      - name: Build kraken-app-hub container
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/app-hub/Dockerfile
          push: true
          tags: cloudnexusopsdockerhub/kraken-app-hub:${{ steps.vars.outputs.docker-image-tag }}


      - name: Build kraken-app-agent container
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/app-agent/Dockerfile
          push: true
          tags: cloudnexusopsdockerhub/kraken-app-agent:${{ steps.vars.outputs.docker-image-tag }}

      - name: Build kraken-app-portal container
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/app-portal/Dockerfile
          push: true
          tags: cloudnexusopsdockerhub/kraken-app-portal:${{ steps.vars.outputs.docker-image-tag }}
