name: Sync to Ent Repo

on:
  push:
    branches:
      - 'main'

jobs:
  update-manifests:
    name: Update Deployment Manifests for Dev env in Cloudnexus
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Auth as Github App
        id: github-auth
        uses: zqdou/kraken/.github/actions/github-app-get-token@main
        with:
          repositoryNames: '${{ github.event.repository.name }}'
          codePermission: write
          pullRequestPermission: write
          appID: '${{ secrets.SYNC_GITHUB_APP_ID }}'
          privateKey: '${{ secrets.SYNC_GITHUB_APP_PRIVATE_KEY }}'
          installationId: '${{ secrets.SYNC_GITHUB_APP_INSTALLATION_ID }}'
          

      - name: Checkout deployment config
        uses: actions/checkout@v4
        with:
          token: '${{steps.github-auth.outputs.github-token }}'
          fetch-depth: 0

      #- name: Sync to target repo
      #  env:
      #    GITHUB_TOKEN: '${{ steps.github-auth.outputs.github-token }}'
      #    ENV: dev
      #    INFRA: kraken
      #  run: |      
      #    git remote add target git@github.com:zqdou/kraken-ent.git
      #    git push target HEAD:main

      #- name: Sync to target repo with PAT
      #  env:
      #    GITHUB_TOKEN: '${{ secrets.SYNC_GITHUB_PAT }}'
      #  run: |      
      #    git remote add target git@github.com:zqdou/kraken-ent.git
      #    git push target HEAD:main
      - name: Commit files
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -a -m "Add changes"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.SYNC_GITHUB_PAT }}
          branch: main
          repository: git@github.com:zqdou/kraken-ent.git
          force_with_lease: true