name: Sync to Ent Repo

on:
  push:
    branches:
      - 'main'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Auth as Github App
        id: github-auth
        uses: zqdou/kraken/.github/actions/github-app-get-token@main
        with:
          repositoryNames: '${{ github.event.repository.name }}'
          codePermission: write
          pullRequestPermission: write
          appID: '${{ secrets.SYNC_GITHUB_APP_ID }}'
          privateKey: '${{ secrets.SYNC_GITHUB_APP_PRIVATE_KEY }}'
          installationId: '${{ secrets.SYNC_GITHUB_APP_INSTALLATION_ID }}'
          

      - name: Checkout source repository        
        uses: actions/checkout@v4
        with:
          token: '${{steps.github-auth.outputs.github-token }}'
          fetch-depth: 0

      #- name: Sync to target repo
      #  env:
      #    GITHUB_TOKEN: '${{ steps.github-auth.outputs.github-token }}'
      #    ENV: dev
      #    INFRA: kraken
      #  run: |      
      #    git remote add target git@github.com:zqdou/kraken-ent.git
      #    git push target HEAD:main

      #- name: Sync to target repo with PAT
      #  env:
      #    GITHUB_TOKEN: '${{ secrets.SYNC_GITHUB_PAT }}'
      #  run: |      
      #    git remote add target git@github.com:zqdou/kraken-ent.git
      #    git push target HEAD:main

      - name: Push to destination repository
        run: |
          git config --global user.name "cloudnexus-gha-actions[bot]"
          git config --global user.email "57290432+cloudnexus-gha-actions[bot]@users.noreply.github.com"
          ls -al